### ISSUE TITLE
Reduce header height on mobile

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#101]
The header takes up a lot of space on the mobile phone, this issue is to make the height smaller when using mobile. The area to reduce is highlighted below:

<img width="502" alt="Screen Shot 2021-11-26 at 11 27 41 AM" src="https://user-images.githubusercontent.com/5077880/143609742-aeff7d53-68cd-40e9-8f87-28b152ef908a.png">

**Comment by mindsgn** [comment]
would love to attempt this for my first bounty.

**Comment by mindsgn** [comment]
I have finished this bounty: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/104

**Comment by mikeghen** [comment]
Thanks @mindsgn! 👏
