### ISSUE TITLE
Extend decimal precision on deposit amount

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#112]
<img width="471" alt="Screen Shot 2021-12-01 at 2 10 29 PM" src="https://user-images.githubusercontent.com/5077880/144298254-35f57e23-3aa3-4cb6-a1bd-7574f70d58a2.png">

**Comment by elvijsTDL** [comment]
Done in #113

**Comment by mikeghen** [comment]
Thanks @elvijsTDL 👏
