### ISSUE TITLE
Show app even when Metamask not installed

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#115]
Currently, if you don't have a browser wallet, the app is hidden. This reduces visibility for people who are just trying to get a look at the app. 

Everything in the app should render (Total Value Streaming, Total Streamers, rexLP yield %, $RIC price, etc.), except the personal stream details and the ability to do transactions will obviously not be enabled (obviously because there's no wallet connected)

![image](https://user-images.githubusercontent.com/62968241/144718276-f3822341-46a0-4a7c-ae06-bba3c18d50ed.png)

**Comment by mikeghen** [comment]
This probably warrants a larger bounty so I raised it to 5000

**Comment by msoni89** [comment]
@mikeghen I will take care of it.

**Comment by mikeghen** [comment]
Nicely done @msoni89
