### ISSUE TITLE
Next Distribution In... animation

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#121]
Note: To be completed once each Ricochet product has been separated into individual tabs. Will be marked as "help wanted" when ready

![image](https://user-images.githubusercontent.com/62968241/145092741-0c66045d-8fbe-4613-a2e8-91370402ba10.png)

Put an animation that shows when the next distribution is to occur. As of writing this, distributions for rexMarkets are at 20-minute intervals, the rexLaunchpad interval is at 20-minute intervals, and the rexLP interval is at 60 minutes. You'd want to appropriate the animation to that.

A good concept would be to use a loading circle like below to show this along with some lingo explaining that it's the time until the next distribution hits (tooltip, maybe?).

![image](https://user-images.githubusercontent.com/62968241/145093430-a710bae4-0fd1-440b-8960-bb3d29b45996.png)

**Comment by dreamdaura** [comment]
Hi, i want to take this issue

**Comment by mindsgn** [comment]
got the animation working just finding a way to get when the next distribution will happen.

**Comment by mindsgn** [comment]
please check this out. https://github.com/Ricochet-Exchange/ricochet-frontend/pull/220

**Comment by josealonso** [comment]
@mindsgn, I read your PR on this. Can this issue be closed ?

**Comment by mindsgn** [comment]
hey, can you test the PR here: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/264
