### ISSUE TITLE
Approve Button Loading when not Loading

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#124]
The approve button just spins sometimes without me doing anything
<img width="813" alt="Screen Shot 2021-12-11 at 11 38 11 AM" src="https://user-images.githubusercontent.com/5077880/145684438-292a30cd-1627-4431-a0f8-df1c52a603d6.png">
And when I try to downgrade I get all these spinners
<img width="706" alt="Screen Shot 2021-12-11 at 11 32 30 AM" src="https://user-images.githubusercontent.com/5077880/145684440-5adb2296-1877-46b4-aa69-aa4a894e64e4.png">

**Comment by msoni89** [comment]
@mikeghen I will take care of it.

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/145692413-7e63df85-7c43-4c28-b9b0-877dbfb05c49.png)
![image](https://user-images.githubusercontent.com/65469737/145692419-42429c4d-344a-4b30-9821-a724db24cf59.png)
![image](https://user-images.githubusercontent.com/65469737/145692427-7cde93c6-62da-4533-84d3-575f2268d4d6.png)

**Comment by msoni89** [comment]
loading state
![image](https://user-images.githubusercontent.com/65469737/145693476-33d9274a-00fe-41f4-8992-0c79d75a0d11.png)
disabled state
![image](https://user-images.githubusercontent.com/65469737/145693479-0ca7e7e3-dca2-4fe3-8b61-398604e4f698.png)
![image](https://user-images.githubusercontent.com/65469737/145693489-e04a8b79-70ec-41d9-90ce-0b8a22776821.png)
enabled state
![image](https://user-images.githubusercontent.com/65469737/145693506-c7a7b5bf-5774-46db-851c-072ccef9cb41.png)
loading state
![image](https://user-images.githubusercontent.com/65469737/145693516-164534b0-067d-4da7-818b-486573dedda3.png)


downgrade laoding

![image](https://user-images.githubusercontent.com/65469737/145693521-77716e0e-97d6-4c63-9bc8-d04e5f8914bc.png)

**Comment by msoni89** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/128 @mikeghen

**Comment by mikeghen** [comment]
I took a look and this seems to work fine in staging, way to go @msoni89! 👏
