### ISSUE TITLE
Round the main container

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#126]
Make the bottom of the page end cleaner by rounding the edges and removing the discontinuity in the background:
<img width="1375" alt="Screen Shot 2021-12-11 at 2 09 19 PM" src="https://user-images.githubusercontent.com/5077880/145688683-60be09aa-de88-4d36-961a-170ef1257cc6.png">

**Comment by msoni89** [comment]
I will look into it. 


@mikeghen

**Comment by msoni89** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/127

![image](https://user-images.githubusercontent.com/65469737/145690242-4bb16255-7c04-4769-8dca-9642d595b06a.png)

**Comment by mikeghen** [comment]
Nice work @msoni89! 👏 🚰
