### ISSUE TITLE
Display total streaming value for each market in USDC

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#131]
<img width="405" alt="Screenshot 2021-12-12 at 13 49 43" src="https://user-images.githubusercontent.com/3032975/145721460-01a3722c-8939-451d-81fe-e18b7a10c98e.png">

Here the value for this ETH market should be converted to and shown in USDC

**Comment by elvijsTDL** [comment]
@abstractpoint Would just getting the token dollar price from somewhere like coingecko be fine or it has to be specific to USDC? And the end result should be showing something like 37345$/mo instead of 9,437 Eth/mo right? If thats ok I will do this one

**Comment by mikeghen** [comment]
Yes, exactly, show the USD value AND the ETH value, emphasis on USD value

**Comment by elvijsTDL** [comment]
Work in progress

**Comment by elvijsTDL** [comment]
Done in #154

**Comment by mikeghen** [comment]
Nice work @elvijsTDL :clap: 👏
