### ISSUE TITLE
Integration with Wyre for wallet funding

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#132]
There has been discussions with Wyre team and we are ready to add Wyre as a second onramp in addition to Ramp.network in the site.

The objective is to enable support for US users going straight to Polygon from Apple Pay or CC using USDC token. Also an added benefit is to have a backup solution in case primary solution (Ramp.network) currently fails.

Integration would require creating a new Modal dialog that would show 2 logos side by side. This modal needs to appear when you click "Fund Wallet" button on the header. A lambda function needs to be created to sign a request against an API key from Wyre to generate a link that we add to the logo in the modal. After the user completes the flow using Wyre they will be redirected back to wallet page.

If we can create a new modal that would then show a TX id with a link to explorer that would be great to have.

**Comment by mikeghen** [comment]
I followed up with nathan about KYB @abstractpoint

**Comment by mikeghen** [comment]
Im going to close tihs @abstractpoint, we can reopen it if we ever come back to this
