### ISSUE TITLE
Ledger Live DApp Integration

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#134]
This issue involves getting the Ricochet DApp into Ledger Live's app marketplace so Ledger Live users can interact with Ricochet through Ledger Live. 

This is probably the place to start: https://developers.ledger.com/docs/live-app/start-here/

**Comment by alacombe-ledger** [comment]
actually https://developers.ledger.com/docs/dapp/process/

**Comment by alacombe-ledger** [comment]
so the scope is both adaptation of the Ricochet dapp to use Ledger's iframe provider and Nano plugin.

**Comment by msoni89** [comment]
@mikeghen I will take care of it.

**Comment by alacombe-ledger** [comment]
do you need any help with the plugin in `c` @msoni89 or not at all?

**Comment by msoni89** [comment]
@alacombe-ledger definitely I will connect you if needed any help or guidance,

**Comment by msoni89** [comment]
Hi @mikeghen, I and rne (@n4l5u0r) from Ledger are working on this.

**Comment by adrienlacombe-ledger** [comment]
FTR @n4l5u0r is not from Ledger org.

**Comment by msoni89** [comment]
> FTR @n4l5u0r is not from Ledger org.

noted

**Comment by n4l5u0r** [comment]
@mikeghen @msoni89 @adrienlacombe-ledger `c` plugin part is now complete: https://github.com/blooo-io/LedgerHQ-app-plugin-ricochet

**Comment by MrSquiggles13** [comment]
@n4l5u0r is this issue closed? @msoni89 ?

**Comment by msoni89** [comment]
> @n4l5u0r is this issue closed? @msoni89 ?

@MrSquiggles13 @n4l5u0r is working on plugin part, frontend side is ready.

**Comment by n4l5u0r** [comment]
> @n4l5u0r is this issue closed? @msoni89 ?

One last round of optimization is necessary as the smart contracts logic on `CallAgreement` is not something standard within plugin API. So need to write some of the decode custom logic. Hope yo complete this by eod.

**Comment by n4l5u0r** [comment]
@MrSquiggles13 
cc: @msoni89 
code completed on `c` side for the plugin, tests added. : https://github.com/blooo-io/LedgerHQ-app-plugin-ricochet
now time to deploy this on ledger side, will sync with ledger to cover this part.

**Comment by msoni89** [comment]
@mikeghen @MrSquiggles13 this is ready to merge, but if I need to update it's manifest url to support prod.

**Comment by msoni89** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/207
