### ISSUE TITLE
Gnosis Safe Integration

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#135]
This issue involves adapting the frontend so it works when loaded as a Gnosis Safe App.

**Comment by msoni89** [comment]
@mikeghen I will take care of it.

**Comment by MrSquiggles13** [comment]
@msoni89 i need a progress update on this or we will reassign the bounty

**Comment by msoni89** [comment]
@MrSquiggles13 it's already finished and merged into master
