### ISSUE TITLE
Transactions get created with 0 WEI gas price

### ISSUE THREAD

**Issue by elvijsTDL** [Ricochet-Exchange/ricochet-frontend#136]
Very often transactions get created with 0 gas price even if Metamask gas price is set and it causes transactions to get stuck even if you try to speed them up afterwards

![image](https://user-images.githubusercontent.com/77115130/146077772-ec5e1946-108f-4776-92fd-5f44704b507f.png)

**Comment by mikeghen** [comment]
I dont think this is still an issue
