### ISSUE TITLE
Fix IDLE icon size

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#139]
<img width="541" alt="Screen Shot 2021-12-16 at 4 10 03 PM" src="https://user-images.githubusercontent.com/5077880/146449476-c5a8fae0-4786-4d92-a176-740dc0bab492.png">

**Comment by msoni89** [comment]
@mikeghen 
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/142
