### ISSUE TITLE
Notice Banner

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#143]
Add a banner to the top of the app stating:

"Ricochet Exchange has partnered with Idle Finance to offer real-time $IDLE investing. Try the $IDLE rexMarket today"

Kinda like where it says "SIGNUP TODAY AND ..." on this image:

![image](https://user-images.githubusercontent.com/62968241/146651840-088b730f-eab7-4a96-b779-499af55a82db.png)

You'll want to replace that statement with the "Ricochet Exchange has partnered..." and the yellow "SIGNUP NOW" button with "Learn More". That should link to our Medium article here https://medium.com/ricochet-exchange/idle-real-time-investing-is-here-7b69e2484032

Make the banner go above the yellow bar where we say our contracts are unaudited.

![image](https://user-images.githubusercontent.com/62968241/146651908-8ec03eb6-c7f5-4386-9574-693a0156df6f.png)

Stylistically, it should be this ice blue color (#84aad0). 

Nice to have: an "X" on the far right such that a user can make the banner disappear. This earns you $50 extra compensation

This bounty would be convenient such that it could be used in a reusable fashion for future notices we want to provide app users.

**Comment by dreamdaura** [comment]
Hi, want to do this !

**Comment by dreamdaura** [comment]
[#163](https://github.com/Ricochet-Exchange/ricochet-frontend/pull/163#issue-1089263398)

**Comment by jojudre** [comment]
#211

**Comment by MrSquiggles13** [comment]
@jojudre is this issue closed? @sunnyjaycer  did you pay this out?

**Comment by sunnyjaycer** [comment]
I don't think we'll be merging this, but I recall @mikeghen did mention a banner like this may be appropriated for drawing attention to new v2 markets. I suppose we can close for now and then reopen the issue and adjust this code when we revisit.

**Comment by MrSquiggles13** [comment]
@sunnyjaycer  we can leave it alone im gonna just track bounties from now on and do this clean up weekly

**Comment by jojudre** [comment]
@MrSquiggles13 Hi, i can fix this in the future, if it needed

**Comment by mikeghen** [comment]
Closed as not doing
