### ISSUE TITLE
Move Market Price Below User Balance

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#156]
This issue involve removing the token price column from the page and move the market price below the user balance, like shown below:
<img width="358" alt="Screen Shot 2021-12-22 at 10 10 53 AM" src="https://user-images.githubusercontent.com/5077880/147299657-fbb8012f-9888-44e9-b737-8a9a5eb32e70.png">

**Comment by elvijsTDL** [comment]
I will do this one

**Comment by serotoninexperience** [comment]
This issue seems to be resolved.
