### ISSUE TITLE
Show token balances on mobile wallet view

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#157]
Right now the balances of the tokens you hold arent shown, can these balances, supertoken and non-supertoken balance, be shown here? 
<img width="496" alt="Screen Shot 2021-12-23 at 6 40 52 PM" src="https://user-images.githubusercontent.com/5077880/147299817-c62b4c5f-54a3-4c0b-8572-65c867d5795c.png">

**Comment by elvijsTDL** [comment]
I will do this one
