### ISSUE TITLE
Wallet page - rows hanging off

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#165]
![image](https://user-images.githubusercontent.com/62968241/147591162-e295c769-9729-4bca-9646-ef1490a5e07f.png)

The white container section should extend to contain all of the rows the way it does on the Invest tab.

**Comment by dreamdaura** [comment]
hi, i can do this!

**Comment by vaibhavgeek** [comment]
This has been resolve in the PR : https://github.com/Ricochet-Exchange/ricochet-frontend/pull/195  
<img width="1512" alt="Screenshot 2022-01-11 at 8 52 32 PM" src="https://user-images.githubusercontent.com/1227925/148970659-c06ac519-72ff-4e34-8558-e6167b33d0c4.png">
