### ISSUE TITLE
Tutorial button 

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#166]
Add a little tutorial pop out option below rexBank. Should look like what's shown below:

![image](https://user-images.githubusercontent.com/62968241/147591793-34c94458-d6ce-446b-827d-c3e1fdcff2ee.png)

**Comment by nishit-g** [comment]
Hey @sunnyjaycer can I take this on ? Where should the Tutorial button take user ?

**Comment by sunnyjaycer** [comment]
Let's link it to here: https://docs.ricochet.exchange/tutorial/using-the-dapp

Double whammy - they get their tutorial and they're exposed to the docs 😤

**Comment by sunnyjaycer** [comment]
Also @nishit-g, could you capitalize the "S" in "streams" in that top button while you're at it

**Comment by nishit-g** [comment]
Hey @sunnyjaycer , is this GTG ? 

<img width="1440" alt="Screenshot 2021-12-30 at 3 52 22 PM" src="https://user-images.githubusercontent.com/32142878/147743142-6a68c7a6-dab0-48e6-b182-36ef59d54656.png">

**Comment by sunnyjaycer** [comment]
Almost. Tiny tweaks:

- get rid of that faint blue background around the rexBank and Tutorial buttons so it's just white like before
- add back the pop out icon to the rexBank button
- add a space between "tutorial" and the pop out icon on the tutorial button

**Comment by nishit-g** [comment]
@sunnyjaycer , updated !

Just wanted to make sure, currently the rexBank option doesn't take user to any external link, right ? ( As currently in the app it just renders other component, I have also removed the active class styling from this as it looked weird)

<img width="1440" alt="Screenshot 2021-12-30 at 8 36 33 PM" src="https://user-images.githubusercontent.com/32142878/147763496-70630346-cca8-4beb-87f5-b509ac1d4831.png">

**Comment by sunnyjaycer** [comment]
Oh my bad @nishit-g! The rexBank button actually should have that faint blue background. I forgot that we integrated it into the app already!

**Comment by sunnyjaycer** [comment]
All good to go otherwise 💯

**Comment by nishit-g** [comment]
in #175

**Comment by sunnyjaycer** [comment]
Great work @nishit-g. Looks like that video icon didn't appear when your code was added to the app, but that's an easy future fix.
