### ISSUE TITLE
Max Button

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#17]
Add a button such that when your upgrading all your tokens you don't have to put in the number manually and can just hit max. Will have to put a buffer for the downgrading because a user may already be streaming and hence the balance is dynamically decreasing.

**Comment by abstractpoint** [comment]
Nice one, will attempt at his today. Thanks for tagging me

**Comment by abstractpoint** [comment]
In progress 👍
