### ISSUE TITLE
$0 when wallet not connected

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#170]
#154 Introduced an issue where USD values show up as 0 when no wallet is connected. The $0 value should be an actual value.
<img width="277" alt="Screen Shot 2021-12-30 at 10 07 43 AM" src="https://user-images.githubusercontent.com/5077880/147763803-707008d7-f836-46cd-8b8c-a974c065644e.png">

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/147765920-5f2c981b-e42c-4a76-be5f-98ad9d86509d.png)
