### ISSUE TITLE
More dropdown content in header obscured when open

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#174]
Looks like a problem with z-index after Bank integration
<img width="522" alt="Screenshot 2021-12-30 at 21 09 29" src="https://user-images.githubusercontent.com/3032975/147795673-42be6266-6d95-441a-a164-889c016e00e8.png">

**Comment by msoni89** [comment]
@mikeghen I handled it, please check https://github.com/Ricochet-Exchange/ricochet-frontend/pull/177/files

**Comment by mikeghen** [comment]
Nice work @msoni89, thanks for reporting @abstractpoint ✋
