### ISSUE TITLE
"Max Withdraw" button for Rex Bank

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#178]
This issue is to add a max button to the withdraw collateral on rex bank page (see below). There's a max button for repaying the debt you can reference. 
<img width="1366" alt="Screen Shot 2022-01-01 at 12 18 07 PM" src="https://user-images.githubusercontent.com/5077880/147856255-ceb8241f-b8f9-4968-8683-6292a9e354d9.png">

**Comment by jasonngov** [comment]
Working on this as first issue!

**Comment by elvijsTDL** [comment]
@mikeghen Shouldn't this issue be in https://github.com/Ricochet-Exchange/rex-bank-frontend ?

**Comment by jasonngov** [comment]
@mikeghen Interested in picking this up. Would you mind assigning me the ticket?

**Comment by rashtrakoff** [comment]
Hey @jasonngov , are you still interested in this issue ? I can assign you to the same if you are.

**Comment by jasonngov** [comment]
@rashtrakoff  Yes, please do.
