### ISSUE TITLE
Add ENS avatar support

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#179]
Something like this

![Screenshot 2022-01-05 at 9 18 10 AM](https://user-images.githubusercontent.com/69431456/148157745-2a12f161-3089-4567-b29f-949f53891109.png)

**Comment by mikeghen** [comment]
@bigint, I raised the bounty on this since it hasn't gotten done in 20+ days, I hope this helps

**Comment by bigint** [comment]
@mikeghen I'll take care 🤗

**Comment by josealonso** [comment]
My avatar is as it were @spitko's. @spitko, let me know when this is merged, so I can close this issue. Thanks !!

**Comment by mindsgn** [comment]
@bigint  I think some worked on this: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/274

**Comment by mindsgn** [comment]
I was not able to review since I do not have an ens avatar.

**Comment by spitko** [comment]
Yes, this is done but only tested locally by me.
If anyone has an ENS avatar, please confirm if it shows up in the PR env, thanks.

**Comment by josealonso** [comment]
@spitko, why is this issue still opened ?

**Comment by bigint** [comment]
@josealonso avatar integrations is not made by me, but yes avatar works in staging so we can close it 👍🏻

**Comment by josealonso** [comment]
> @josealonso avatar integrations is not made by me, but yes avatar works in staging so we can close it 👍🏻

I know. You were not around when the other developer did it. These things happen in big projects. Closing it, thanks !!
