### ISSUE TITLE
Improve README design of this repo

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#180]
It would be great if we have better readme with badges, links and docs

**Comment by lucasz-hu** [comment]
@samirsalem How is progress on this?

**Comment by bigint** [comment]
will submit a PR today @lucasz-hu

**Comment by bigint** [comment]
![image](https://user-images.githubusercontent.com/69431456/152632895-bb3ca4c7-a439-4e99-87d3-9a03d39dae45.png)

@lucasz-hu

**Comment by lucasz-hu** [comment]
Look's good! Was just browsing through older issues, glad to see it's done now. :)
