### ISSUE TITLE
Center align icons UPGRADE and DOWNGRADE icon

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#182]
![Screenshot 2022-01-05 at 9 28 54 AM](https://user-images.githubusercontent.com/69431456/148158596-9528091c-3a82-414a-8c41-56b2d4c1b815.png)

**Comment by vaibhavgeek** [comment]
@bigint / @mikeghen This seems like an issue from my work, please assign this to me.

**Comment by vaibhavgeek** [comment]
Screenshot of centered icons 
<img width="1512" alt="Screenshot 2022-01-11 at 8 43 46 PM" src="https://user-images.githubusercontent.com/1227925/148969080-167c83a2-6290-40b9-95df-520b76d7e0d9.png">

**Comment by vaibhavgeek** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/195

**Comment by elvijsTDL** [comment]
@vaibhavgeek Might be a little bit nitpicky, but it would be great to see the Currency and the upgrade/downgrade buttons be right aligned to the headers like rest of the collumns , I think it would give a more polished look , and looks like the lines for some of the collumns are gone too

**Comment by vaibhavgeek** [comment]
@elvijsTDL The lines for some of the columns did not exist by design in the first place, the idea was to separate different sections of the table.

**Comment by vaibhavgeek** [comment]
@elvijsTDL I have right aligned the buttons. 

<img width="1427" alt="Screenshot 2022-01-17 at 12 38 12 PM" src="https://user-images.githubusercontent.com/1227925/149723318-53699bf4-937a-46db-9227-e830c1bd33ae.png">

**Comment by mikeghen** [comment]
Is this done?

**Comment by vaibhavgeek** [comment]
Yes, @mikeghen , it has been approved and merged as well
