### ISSUE TITLE
Align tutorial link to left side

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#184]
![Screenshot 2022-01-05 at 2 04 36 PM](https://user-images.githubusercontent.com/69431456/148186089-84e20bf0-8291-4fc5-bd83-b31e745aeae4.png)

**Comment by mindsgn** [comment]
done: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/213

**Comment by mindsgn** [comment]
@mikeghen please close this.
