### ISSUE TITLE
Add cursor pointer to more dropdown button/icon

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#185]
![Screenshot 2022-01-05 at 2 07 35 PM](https://user-images.githubusercontent.com/69431456/148186556-4961c2b0-b82d-4764-80fc-4604f337a166.png)

**Comment by mindsgn** [comment]
Done: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/212

**Comment by mindsgn** [comment]
@mikeghen please close this.
