### ISSUE TITLE
RIC token logo change

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#187]
Currently, the RIC token is represented just with the black Ricochet logo here on the rexLaunchpad

![image](https://user-images.githubusercontent.com/62968241/148256888-c2627474-711a-4a7f-95e2-185ee1fab583.png)

Replace that with the new RIC token logo provided below

https://drive.google.com/drive/u/1/folders/11qupOOgvlxhPpTsJnfaXL2IoSfNgLXE3

**Comment by jasonngov** [comment]
Working on this.

**Comment by jasonngov** [comment]
![image](https://user-images.githubusercontent.com/40685033/148295778-297a6bd4-d760-400e-95d3-4c9d0324437d.png)

**Comment by sunnyjaycer** [comment]
Looks too small @jasonngov, could you size it up to the usdc logo?

**Comment by jasonngov** [comment]
![image](https://user-images.githubusercontent.com/40685033/148306922-f8dfb9d4-e36c-449d-b1aa-6d8d127d570e.png)
Done.

**Comment by sunnyjaycer** [comment]
Perfect. Thanks for the speedy work @jasonngov

**Comment by mikeghen** [comment]
I closed #188, if you two want to change the logo, get the logo approved by token holders first. Also, this PR was open for 9 days and neither of you said anything about getting it in, so I question whether anyone wants this done.

**Comment by jasonngov** [comment]
Hey Mike, I gave a PR update on 1/05 about this being completed in the Discord. No one reviewed it?

**Comment by mikeghen** [comment]
Lets take this conversation to #proposals if you two want to change the logo
