### ISSUE TITLE
Repaying USDCx to bank not working

### ISSUE THREAD

**Issue by d3centra** [Ricochet-Exchange/ricochet-frontend#208]
When accessing the rexVault via https://app.ricochet.exchange/vaults, it is not possible to repay USDCx to the bank - at least if the user hasn't prior given the allowance to access funds through https://bank.ricochet.exchange/vaults.

This issue has to do with the fact that after clicking "give allowance", no MetaMask pop-up is opened that the user could sign. 

Interestingly enough, this apparently only happens to users if they haven't already given the allowance through https://bank.ricochet.exchange/vaults (here it's working). 

<img width="339" alt="allowance" src="https://user-images.githubusercontent.com/95552251/149411100-629146a8-41b8-4d83-b876-b8957d4de9f8.PNG">

**Comment by jasonngov** [comment]
Working on this ticket.

**Comment by mikeghen** [comment]
Can someone try to reproduce this issue?

**Comment by josealonso** [comment]
Is this still an issue, @d3centra ?

**Comment by josealonso** [comment]
I just tried to repay from https://staging.ricochet.exchange/vaults and I don't see this issue. I think this can be closed, @mikeghen

**Comment by zhyd1997** [comment]
@josealonso maybe the same issue: https://discord.com/channels/862796510604296263/864667072357597185/942691001871515668

**Comment by josealonso** [comment]
I put my avatar on behalf of @Seroxdesign

**Comment by mikeghen** [comment]
#520 is the same issue
