### ISSUE TITLE
Expand input field on Wallet page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#218]
The input box is too small:
<img width="600" alt="Screen Shot 2022-01-15 at 8 10 14 AM" src="https://user-images.githubusercontent.com/5077880/149623200-adeca68e-8a34-4040-b3fc-3d494a2efcf5.png">

**Comment by nishit-g** [comment]
Working on this @mikeghen

**Comment by jasonngov** [comment]
I also am getting started on this.

**Comment by jasonngov** [comment]
![image](https://user-images.githubusercontent.com/40685033/149637626-18595358-d2eb-494a-bb6d-592802562f16.png)
Looks like this has already been addressed.

**Comment by mikeghen** [comment]
I still have this issue

**Comment by jasonngov** [comment]
I am unable to reproduce this on local or in PROD. I'll defer for someone else to take a look.

**Comment by mikeghen** [comment]
Thank you @spitko 👏
