### ISSUE TITLE
Make Balance and Address readable

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#221]
<img width="260" alt="Screen Shot 2022-01-17 at 10 41 39 AM" src="https://user-images.githubusercontent.com/5077880/149799754-da1d3ef7-d208-4ff5-9e5e-60d5d9966d77.png">

Use locale strings (10K) and make sure the address is ALWAYS visible

**Comment by msoni89** [comment]
@mikeghen I will take care of this.

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/149832428-d6226cf9-2a53-4fbd-9d80-054ca650b602.png)
![image](https://user-images.githubusercontent.com/65469737/149833155-80769161-6341-48d5-b56f-8bd370a3c580.png)
![image](https://user-images.githubusercontent.com/65469737/149833263-ace2e396-b029-447e-a91a-29c9b82c491f.png)
![image](https://user-images.githubusercontent.com/65469737/149833310-375a7602-0746-4104-8430-a521dc0f939d.png)
![image](https://user-images.githubusercontent.com/65469737/149833385-c3a73443-3062-41f3-8a05-3d00996a772e.png)
![image](https://user-images.githubusercontent.com/65469737/149833417-41e685f8-4f37-46c7-85b3-3610f65528aa.png)
![image](https://user-images.githubusercontent.com/65469737/149833483-8156ea16-52c3-4e28-9c8a-840aff963334.png)
![image](https://user-images.githubusercontent.com/65469737/149833517-829f1ac4-1461-4914-9e13-2a5075415252.png)
