### ISSUE TITLE
Redesign REX Bank Page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#249]
The current page has A LOT of white space, that's the main issue. 
Secondly, its not so easy to see what's borrow token and collateral token, you have to look at token symbols, it would be better to use token symbols which are already in the assets folder
Third, I think we will have a lot of REX Banks in the future, so I would like to have the interface look more like Aave's markets page, things are pretty condensed into Rows. I think we should also have rows like Aave
<img width="1596" alt="Screen Shot 2022-01-20 at 7 49 49 AM" src="https://user-images.githubusercontent.com/5077880/150341741-e2c68d2f-ed24-4a4e-90ef-38a07af02495.png">
ave, see attached screenshot:

**Comment by jasonngov** [comment]
To clarify, this would be a complete overhaul of our existing UI in the Banks page?  Would @mikeghen or @sunnyjaycer be able to provide a specific mockup for REX Bank, or do we just to use AAVE as the template. I can explore potentially taking on this ticket if the requirements are well-defined before development.
![image](https://user-images.githubusercontent.com/40685033/150789180-832364a8-24dc-4c49-a7ea-0b509d3d456c.png)

**Comment by josealonso** [comment]
Are you working on this, @jasonngov ?

**Comment by jasonngov** [comment]
Yes, I should have the final prototype done by end of week.

**Comment by mikeghen** [comment]
@bigint is on it :+1:
