### ISSUE TITLE
Add RIC on the wallet page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#250]
Please, why isn't it there already 😿 
<img width="567" alt="Screen Shot 2022-01-20 at 2 11 47 PM" src="https://user-images.githubusercontent.com/5077880/150406404-597ebebc-d424-4bdd-a3da-f0ba6200dff4.png">

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/150421832-aa9de1cc-32b0-436d-b891-47b1f05908f9.png)
