### ISSUE TITLE
Dynamically set Priority gas

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#259]
Seems the priority fee is hardcode to 2.5, other apps like Sushiswap have it getting set dynamically. This task is to make the prioty fee dynamic so transactions wont get stuck under eip-1559
<img width="265" alt="Screen Shot 2022-01-22 at 11 49 24 AM" src="https://user-images.githubusercontent.com/5077880/150648138-d3652c60-dc15-4b73-8c4b-7a03790ea96e.png">

**Comment by jasonngov** [comment]
I can explore this.

**Comment by MrSquiggles13** [comment]
Oh no again i gotta stop claiming these in the discord

**Comment by jasonngov** [comment]
Completed in #260

**Comment by mikeghen** [comment]
Nicely done team

**Comment by mikeghen** [comment]
@jasonngov please implement this on all the transactions in the app, you didn't do this for any of the bank transactions that show up at the bottom of `ethereum.ts`

**Comment by MrSquiggles13** [comment]
@mikeghen I'd do it but i let him have the entire bounty 😂

**Comment by mikeghen** [comment]
@MrSquiggles13 problem is @jasonngov was already paid the bounty, maybe he will pay you to clean this up, its first come first serve but this bounty was paid and not completed, its my fault for thinking it was done completely without me verifying it, you can have 20% of the bounty if you do it and we can call it a QA bounty for you

**Comment by MrSquiggles13** [comment]
@mikeghen I mean thats partly my fault as well. I can just clean it up and from now on if i collab with someone ill make sure its completely done as well as take my part of the bounty

**Comment by jasonngov** [comment]
Thought the payout was because all transactions I needed were verified. @MrSquiggles13 feel free to take on this issue, I will not be able to work on this today.

**Comment by josealonso** [comment]
@jasonngov's part is done. @MrSquiggles13 is doing it for the bank transactions.

**Comment by MrSquiggles13** [comment]
I swear i already did this.... Gonna take a look

**Comment by josealonso** [comment]
@MrSquiggles13, do you have a PR for this ?

**Comment by MrSquiggles13** [comment]
@josealonso  https://github.com/Ricochet-Exchange/ricochet-frontend/pull/295 and in there you can see that it was already handled even before mine

**Comment by josealonso** [comment]
> @josealonso #295 and in there you can see that it was already handled even before mine

Thank you. I wish people closed their issues after seeing their PRs has been merged. Closing it now.
