### ISSUE TITLE
Contributor Guide

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#265]
Make a contributor guide `CONTRIBUTE.md`

**Comment by samirsalem** [comment]
i'll take this task if it's ok for you

**Comment by lucasz-hu** [comment]
How is progress on this?

**Comment by josealonso** [comment]
Closing it thanks to this PR ---> https://github.com/Ricochet-Exchange/ricochet-frontend/pull/305

**Comment by josealonso** [comment]
I'm sorry I was too quick to close this issue. I am reopening it.
That document needs an explanation about the continuous integration tool, @bigint.
