### ISSUE TITLE
REXBank Action Button incorrect

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#266]
Always says withdraw, even when deposit/repay/borrow:
<img width="874" alt="Screen Shot 2022-01-25 at 9 31 14 AM" src="https://user-images.githubusercontent.com/5077880/150996425-c6919c42-2655-45f5-bd37-69091ca2494d.png">

**Comment by jasonngov** [comment]
Done in #267

**Comment by mikeghen** [comment]
Nice work, thanks for the quick turn around @jasonngov
