### ISSUE TITLE
Adding feedback on hovers to improve UX

### ISSUE THREAD

**Issue by serotoninexperience** [Ricochet-Exchange/ricochet-frontend#271]
I propose adding feedback to user input such as hovering over buttons or switching between pages to make the experience more intuitive.
(Similar work to background color change on user setting dropdown.)
So far I've caught 3 different places this could be implemented

**Comment by mikeghen** [comment]
What would this look like? share those 3 places you want to implement this

**Comment by josealonso** [comment]
@serotoninexperience, let us know if you're working on this. You opened a bunch of issues !!

**Comment by serotoninexperience** [comment]
Not working on this anymore since we've changed the layout, will close issue.

**Comment by josealonso** [comment]
Great, thanks !!
