### ISSUE TITLE
Improving Nav and dashboard look 

### ISSUE THREAD

**Issue by serotoninexperience** [Ricochet-Exchange/ricochet-frontend#272]
![proposal2](https://user-images.githubusercontent.com/69639595/151095139-1841d397-8ab3-493b-a5e2-39153456570f.jpg)

I propose improving the dashboard and left side nav to improve user experience and allow for better navigation/more intuitive design

**Comment by serotoninexperience** [comment]
This should be done.

**Comment by mindsgn** [comment]
thank you @serotoninexperience.
