### ISSUE TITLE
Text size issues

### ISSUE THREAD

**Issue by serotoninexperience** [Ricochet-Exchange/ricochet-frontend#275]
Mobile version text is not formatted correctly causing this issue 

![Screenshot_20220126-152545_Samsung Internet.jpg](https://user-images.githubusercontent.com/69639595/151241824-f8be1464-ceaa-46f2-830c-6918c63228cc.jpg)

I propose removing the upgrade downgrade buttons and replacing them with arrows that can stack on top of eachother.  

Also remove the word balance from the column titles. 
(It's in the wallet page so no context will be lost)

This will improve text readability and overall look of the page.

**Comment by josealonso** [comment]
Are you working on this, @serotoninexperience ?

**Comment by serotoninexperience** [comment]
Yes, working on this. Taking long because changing 1 item changes all of them.

**Comment by serotoninexperience** [comment]
Fixed text issues and did minor improvements to overall styles:
PR below:
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/297
