### ISSUE TITLE
Remove the Fund Wallet button

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#279]
Since we're a DAO, no payment processor will work with us, so we'll have to remove this, sadly 😿 
<img width="510" alt="Screen Shot 2022-01-28 at 10 42 26 AM" src="https://user-images.githubusercontent.com/5077880/151577342-f677bc83-bdc0-469a-83af-5287700a857b.png">

**Comment by MrSquiggles13** [comment]
On it

**Comment by lucasz-hu** [comment]
#280 Finished

**Comment by MrSquiggles13** [comment]
@lucasz-hu  next time make sure you get approved to work on a bounty before you undercut someone else.  @mikeghen  made this issue for me to do and gave me this bounty to work.

**Comment by lucasz-hu** [comment]
@MrSquiggles13 Sorry I read on discord that bounties were no longer going to be claimed and done on a first-delivered basis. Could we get clarification about this?

I'm fine with giving you the bounty though.

**Comment by MrSquiggles13** [comment]
@lucasz-hu @mikeghen  was just suggesting that we never agreed upon it. You already did it so just take it

**Comment by josealonso** [comment]
@lucasz-hu, did you claim the bounty for this task ?

**Comment by lucasz-hu** [comment]
@josealonso Yes, however my PR was closed? Not sure why. I might've been too quick to submit I guess.

**Comment by josealonso** [comment]
The button is still there. I was too quick when I closed it, sorry. Reopening it.

**Comment by josealonso** [comment]
@lucasz-hu, not sure whether Ricochet will work with a payment processor. I guess it won't. You can ask @mikeghen or @sunnyjaycer.

**Comment by josealonso** [comment]
This button is not present in staging, so I guess this issue can be closed. @mikeghen, @sunnyjaycer

**Comment by abhisheknaiidu** [comment]
@josealonso can i work on this, if no one is working?

**Comment by josealonso** [comment]
@abhisheknaiidu, I'm going to close it, because the button is not present in https://staging.ricochet.exchange/
