### ISSUE TITLE
Add message to alert uses of the Superfluid Deposit

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#28]
We need to have a similar message in our application

<img width="384" alt="Screen Shot 2021-09-09 at 11 17 37 AM" src="https://user-images.githubusercontent.com/5077880/132714114-3be7cf75-c19e-4ec7-b78e-37b495f05421.png">

**Comment by jo-chemla** [comment]
PR Screenshot: 
![image](https://user-images.githubusercontent.com/16822841/140440365-cf0c7296-7225-4f8a-94a6-7dbb245d5809.png)
