### ISSUE TITLE
Make Sure the app `yarn builds` successfully before passing check

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#282]
The build to staging/production still fails periodically because there are linting errors when running `yarn build`. This issue is to run `yarn build` to make sure the build doesn't break when its deployed out to staging/production environments.

**Comment by mikeghen** [comment]
This is an example of a commit that broke the build: 
https://github.com/Ricochet-Exchange/ricochet-frontend/commit/bba152efb98d38785fe6b9fbde61cecc5df4128d

**Comment by samirsalem** [comment]
Issue has been fixed, Added a build step at the beginning of the workflow and increased heap memory to avoid heap JS error.
if build fails workflow fails and env is not created

**Comment by mikeghen** [comment]
@samirsalem, thank you 🙏

**Comment by josealonso** [comment]
@samirsalem, did you open a PR ? I don't know how you handle issues with the CI tool. Let me know if I can close it. Thanks !!

**Comment by samirsalem** [comment]
@josealonso to answer your wuestion,  in order to work changes must be merged in main branch, you can close this PR :)
