### ISSUE TITLE
Can't approve repayment to the bank

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#287]
see video

https://user-images.githubusercontent.com/5077880/151675662-a661c8a3-6ed7-457e-9e81-a2bbbae609cc.mov

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/151679512-514ec6a5-462a-4d98-ba12-3b0f21dc1f2e.png)

 It works fine, if you have enough approved value then it automatically switches to repay field, or else it will trigger approval. 

Below code snippoet 
![image](https://user-images.githubusercontent.com/65469737/151679536-5908ce3f-97b5-4d74-ae9a-8ec95c6d5585.png)

**Comment by josealonso** [comment]
@msoni89, did you open a PR ?

**Comment by mikeghen** [comment]
No one is able to reproduce it so Im closing it
