### ISSUE TITLE
Include links to REXMarket contract addresses in the frontend 

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#291]
Im not sure where it would be best to put it but we need to include a link to Polygonscan in the frontend so its easy to jump to the contracts there. As a customer, I would want to be able to see the contract addresses on chain so I can review them (either the code or just the historic activity on chain)

**Comment by josealonso** [comment]
@mikeghen said on discord 
```
It's good first issue for someone looking to contribute to the frontend, no urgency so if you're an existing front end contributor, please leave this for a few days to give someone new a chance to try it, if no one new steps up by Friday, then anyone can grab it
```

**Comment by serotoninexperience** [comment]
I will work on this tomorrow if everyone is okay with that

**Comment by Seroxdesign** [comment]
Progress;

1. created a contract page to display all currently used contracts. 
2. added the gitbook page in the user setting docs
3. Added links in different sections of the site (rexbank/rexvault/refer)
4. Created PR, waiting for review.

**Comment by josealonso** [comment]
@Seroxdesign, where is the link to your PR ?

**Comment by Seroxdesign** [comment]
PR: 

https://github.com/Ricochet-Exchange/ricochet-frontend/pull/322

**Comment by Seroxdesign** [comment]
Closed PRs and reworking this.

**Comment by Seroxdesign** [comment]
Update, this is almost done should Have it 02/13

**Comment by Seroxdesign** [comment]
This is complete,
PR:
#381
