### ISSUE TITLE
Create visual feedback for Vault page transactions.

### ISSUE THREAD

**Issue by serotoninexperience** [Ricochet-Exchange/ricochet-frontend#292]
When creating a vault the user must deposit some funds (RIC) to gain access to USDc borrowing. 
On user's attempt to repay borrowed USDc a transaction starts in the metamask extension opening a pop up the user must approve.

The issue is while this is happening the Front-end hides all interactive buttons and doesn't show progress for the metamask transaction, in this 2 to 10 minute window users might be tempted to refresh the browser or move to another page. 

![ric 1](https://user-images.githubusercontent.com/69639595/151709973-eea5f5aa-4713-4311-984f-99570a14e390.jpg)
![loading](https://user-images.githubusercontent.com/69639595/151709978-1ef58eb7-3663-451b-93b8-6d714919af65.jpg)
![j3](https://user-images.githubusercontent.com/69639595/151709985-31068733-aaa0-43a8-88b2-13055b84f6b1.jpg)

I suggest we add a loading bar, a card warning user transaction is in process and a pop up to deter users from refreshing

**Comment by josealonso** [comment]
@serotoninexperience, sorry to bother you again. Should I assign this task to you ?

**Comment by serotoninexperience** [comment]
Yes please.

**Comment by serotoninexperience** [comment]
Updates:

Still working on this issue, have to read all the bank / vault page code to ensure no breaking mistakes are made.
Will need another 2 to 3 days to complete.

**Comment by serotoninexperience** [comment]
Complete
