### ISSUE TITLE
List REXTwoWayMarket

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#298]
The REXTwoWay market USDC<>ETH is live at this contract address: 0xF6a03FCf12Cdc8066aFaf12255105CA301E15ba6

This is ready to be added to the app, but as a two-way market it works a little different, here's some notes on how:

* The two way market is 1 contract address for two tokens, so USDC<>ETH contract needs to support opening streams to the contract
* The approvals are done differently, when approving USDC, the approval needs to be for indexes 0 and 2, for ETH it needs to approve 1, and 3. Table below shows how approvals work:

| Input token | IDA Index | IDA Token |
|------------|-----------|-----------|
| USDCx       | 0                | ETHx        |
| ETHx          | 1                 | USDCx          |
| USDCx       | 2                | RIC    |
| ETHx          | 3                | RIC    |

* When opening a USDCx stream, the app needs to `batchCall` approvals for IDA (0,ETHx) and (2,RIC)
* When opening a ETHx stream, the app needs to `batchCall` approvals for IDA (1,USDCx) and (3,RIC)

Claim this bounty by getting the streaming to the REXTwoWay market working in the app for both USDC and ETH streaming

**Comment by vaibhavgeek** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/299

**Comment by vaibhavgeek** [comment]
<img width="1504" alt="Screenshot 2022-02-03 at 9 15 38 PM" src="https://user-images.githubusercontent.com/1227925/152377013-dcbb6fcd-7cff-4c4a-9072-8d474906baf8.png">

**Comment by mikeghen** [comment]
Im reopening this since @vaibhavgeek's solution is hard coded, it works well so thank you @vaibhavgeek, but will open this up to someone to try to not have it hard coded, this needs to use `exchangeAddress` `inputToken` `outputToken` and other things from `constants/flowConfig.js`

Adding WBTC will have an IDA table like:

| Input token | IDA Index | IDA Token |
|------------|-----------|-----------|
| USDCx       | 0                | WBTCx        |
| WBTCx          | 1                 | USDCx          |
| USDCx       | 2                | RIC    |
| WBTCx          | 3                | RIC    |

**Comment by mikeghen** [comment]
compare the `startFlow` function on this v2 branch to whats on the main branch to see how it should be done

**Comment by vaibhavgeek** [comment]
How to add markets, in `flowConfig.ts`, you need to add to this constant, 
```
export const indexIDA : { input: string, output:string, subsidy?: string, subsidyIndex?: number, inputIndex: number, outputIndex: number }[] = [
  {
    input: USDCxAddress,
    output: WETHxAddress,
    subsidy: RICAddress,
    subsidyIndex: 3,
    inputIndex: 0,
    outputIndex: 1, 
  },
  {
    input: WETHxAddress,
    output: USDCxAddress,
    subsidy: RICAddress, 
    subsidyIndex: 2,
    inputIndex: 1,
    outputIndex: 0, 
  },
];

```

with the respective values of input, output and subsidy tokens.
