### ISSUE TITLE
Add dependabot integration

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#306]
Add dependabot integration to keep all the dependencies up to date 📦 

@mikeghen Please assign to me if there is a bounty 🤗

**Comment by mikeghen** [comment]
Nice work thank you 🙏

**Comment by mikeghen** [comment]
Next up youll fix all the dependancy issues right @bigint 😁

**Comment by bigint** [comment]
Sure @mikeghen I'll take care of breaking dependencies 🤗
