### ISSUE TITLE
Add "Use At Your Own Risk" and a 2% fee message

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#31]
1. "While reviewed by the Superfluid team, these contracts have not been audited, use at your own risk"
    - perhaps in a thin banner on top like what https://mean.finance does
2. "Ricochet takes a 2% fee on swaps"
    - maybe in a banner on the bottom of the page

**Comment by jo-chemla** [comment]
Screenshot of PR: 
![image](https://user-images.githubusercontent.com/16822841/140313711-432f8f12-b3f3-409f-86f8-cf5f94b44903.png)

**Comment by jo-chemla** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/66 should fix the banner on mobile and desktop!
