### ISSUE TITLE
ENS name and avatar are not working

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#310]
![Screenshot 2022-02-06 at 9 23 49 AM](https://user-images.githubusercontent.com/69431456/152667124-96bb9c3c-f532-4d3c-9a17-4dfbc1593fc8.png)

Also along with this I'll improve the account button

@mikeghen Please assign to me if there is a bounty 🤗

**Comment by mikeghen** [comment]
@bigint, can you also use git blame so we know who broke this functionality? I don't like we're redoing this again 😪

**Comment by bigint** [comment]
This issue will fixed by PR: #313
