### ISSUE TITLE
Improve font size and icon size in sidebar

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#311]
![Screenshot 2022-02-06 at 9 24 51 AM](https://user-images.githubusercontent.com/69431456/152667147-56b168ee-7cd5-47c0-ad8b-c035602549ac.png)

We also need to use some good font site wide

@mikeghen Please assign to me if there is a bounty 🤗

**Comment by bigint** [comment]
I'm working on this 🤗

**Comment by josealonso** [comment]
@bigint, this can be assign to other contributor if you are not working on this.

**Comment by bigint** [comment]
@josealonso this is already shipped https://github.com/Ricochet-Exchange/ricochet-frontend/pull/326
