### ISSUE TITLE
Add empty state if there is no search result

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#317]
![image](https://user-images.githubusercontent.com/69431456/152684095-35d1646d-69a2-4dc9-a69c-c6a9a90c3805.png)

@mikeghen Please assign to me if there is a bounty I'll work on this 🤗

**Comment by bigint** [comment]
I'm working on this 🤗

**Comment by josealonso** [comment]
@bigint, this can be assign to other contributor if you are not working on this.

**Comment by bigint** [comment]
@josealonso this is already shipped 🚀
