### ISSUE TITLE
Deploy ricochet in IPFS, a path to decentralisation

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#319]
Document: https://yoginth.notion.site/Fleek-for-Ricochet-fe37071e42674c37ac5136b97e28add2

**Comment by josealonso** [comment]
Is that document the equivalent to a PR, @bigint ? If it is, could you link a pull request, so everyone can see it has to be reviewed ?

**Comment by bigint** [comment]
@josealonso yes there is no code associated with this, all devops works, after v2 @mikeghen told that we can move to IPFS

**Comment by samirsalem** [comment]
I'll also close this and create a new issue according to discussion in discord
