### ISSUE TITLE
Add prettier and lint all the code

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#324]
I'll be happy to work on this, this will be a bit huge effort 🤗

**Comment by josealonso** [comment]
@bigint, I put this label because we already have prettier and linter for the Solidity code. I agree with you, but this decision has to be taken by a frontend team leader. I guess many of us use VSCode or an equivalent tool, where the linter plugin is already installed. Anyway, this has to be integrated by the CI tool and I think it is already done.

**Comment by bigint** [comment]
@josealonso I can see only linter is only available in CI, the prettier is not there and our codebase is not properly prettified.

Yes some has prettier installed in vscode but the prettier configuration should be added to make the prettier works same for all

**Comment by josealonso** [comment]
@bigint, I agree, but you might want to comment this on discord with other developers. We still don't have prettier configured on the main branch of the backend. It takes time. And make sure @samirsalem integrates that in the CI tool. I just removed the *invalid* label.

**Comment by bigint** [comment]
We need wait for @mikeghen, this one need to handled carefully else it will cause conflicts for all open PRs in the repo.

**Comment by mikeghen** [comment]
@abhisheknaiidu, did you also lint all the code? I don't see that in the commit?

**Comment by mindsgn** [comment]
I will take this issue.

**Comment by 0xSero** [comment]
@mindsgn 

Is there any progress on this?

**Comment by mindsgn** [comment]
@Seroxdesign  yes, I will make a PR tomorrow.

**Comment by mindsgn** [comment]
@Seroxdesign done: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/750
