### ISSUE TITLE
add missing `FlowTypes` and `FlowEnum` value.

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#330]
glad to work on this to fix type errors.

**Comment by zhyd1997** [comment]
@mikeghen need double check

https://github.com/Ricochet-Exchange/ricochet-frontend/blob/dcfe50c76d9396be53d4ec93b69cc7689f707f8e/src/constants/flowConfig.ts#L11-L14

https://github.com/Ricochet-Exchange/ricochet-frontend/blob/dcfe50c76d9396be53d4ec93b69cc7689f707f8e/src/store/main/sagas/sweepQueryFlow.ts#L94-L110

**Comment by mikeghen** [comment]
These should be removed, those are all part of V1 contracts, we will add them back as needed

**Comment by mikeghen** [comment]
I just didnt to a good job of removing all the v1 code this is why this is here

**Comment by zhyd1997** [comment]
@mikeghen checking again...

**Comment by zhyd1997** [comment]
@mikeghen Just comment unused `*FlowQuery` variables in PR #341, and it's friendly to reuse if needed in the future.
