### ISSUE TITLE
Fix missing `key` prop warning.

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#332]
`/wallet` page

<img width="1278" alt="missing key prop" src="https://user-images.githubusercontent.com/31362988/152740246-45561713-5cc0-4769-a2db-0e246b609cf6.png">

**Comment by zhyd1997** [comment]
I will quickly fix this issue when there are not many PRs.

**Comment by mikeghen** [comment]
:+1: Thank you @zhyd1997
