### ISSUE TITLE
Some of `UserSettings` component references passed undefined props -- `isReadOnly` and `language`.

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#333]
https://github.com/Ricochet-Exchange/ricochet-frontend/blob/dcfe50c76d9396be53d4ec93b69cc7689f707f8e/src/components/layout/UserSettings/index.tsx#L8-L14

**Comment by zhyd1997** [comment]
@mikeghen need double check.

**Comment by mikeghen** [comment]
Not sure what this is but @zhyd1997, have a look and open a PR if you can fix it

**Comment by zhyd1997** [comment]
@mikeghen I will
