### ISSUE TITLE
Creating a loading page.

### ISSUE THREAD

**Issue by Seroxdesign** [Ricochet-Exchange/ricochet-frontend#339]
I propose a loading screen. 
Perhaps with an animation or dynamic text to give out important info. 

My reasoning behind this is the bank/vault issue, when you go straight to the vaultpage it will always route you back to the Bank page first. 

Also first load of the site takes time, so it would be useful to route people to the bank page first, we can have this happen behind the loading screen.

**Comment by Seroxdesign** [comment]
Progress:

Brainstorming possible UIs, will make a mock up in figma then start working on it in app.

**Comment by Seroxdesign** [comment]
### Progress day 2:

Drew out a mock up proposal loading page in Figma.
My thought reasoning behind this is:

We can load bank details while page is loading to solve the Vault-page not loading before the bank page issue [#192](https://github.com/Ricochet-Exchange/ricochet-frontend/issues/196)

Also, a good percentage of people click off the page 2 seconds in when nothing is visually showing progress, using a load page can help with that. 
By showing people Ricochet's numbers we could also instill trust in new users, get devs interested and maybe we can through in links as well so that if a user leaves ricochet can stay open in their tabs. 

![loading page desing](https://user-images.githubusercontent.com/69639595/153285212-b05f803e-bc05-43a7-b071-6e5683a15833.jpg)

![laoding](https://user-images.githubusercontent.com/69639595/153285225-ece02aef-5e73-419c-abcc-43909f61b79c.jpg)

**Comment by josealonso** [comment]
I like the mock up. When can we test this, @Seroxdesign ?

**Comment by sunnyjaycer** [comment]
I like the idea of a loading page, but am not a fan of the way this looks. Could you work with Feldy#3961 in our server to design it? He's the dude behind our new landing page and has a great feel for what looks good.

**Comment by Seroxdesign** [comment]
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/463    PR for this issue
