### ISSUE TITLE
Get Launchpad Stream Rates Working Again

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#340]
These rates need to be right:
<img width="1317" alt="Screen Shot 2022-02-07 at 4 24 41 PM" src="https://user-images.githubusercontent.com/5077880/152874572-2f08701f-d9cf-43a2-ba17-6a10b085c76c.png">

**Comment by zhyd1997** [comment]
@mikeghen the same as the issue #323
