### ISSUE TITLE
Fix `typecheck` pre-commit hook

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#343]
We already have `lint-staged` hook, but it does not work.

`typecheck` pre-commit hook is important for ts codebase

- reduce bugs: a couple of previous issues I submitted are related to type errors.
- we can avoid building errors on PRs, reduced time and machine resources.

It seems that our typescript version is too low (current: `4.0.8`, latest: `4.5.5`), maybe eslint config upgrade is also required, and husky is not configured, so It even doesn't run when using `git commit`.

Another work to do is to fix existing type errors in the codebase.:
<img width="910" alt="type errors" src="https://user-images.githubusercontent.com/31362988/152953141-018fa7b1-ebcd-4db1-a464-6a4f817884fb.png">

**Comment by zhyd1997** [comment]
Setup CI type check too, from DevOps idea.

**Comment by josealonso** [comment]
@zhyd1997, I just went trough your PR. You have to look for reviewers before this issue can be closed.

**Comment by zhyd1997** [comment]
Thank you @josealonso 
I will at next time
