### ISSUE TITLE
Move "Last Distribution" 

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#345]
<img width="1372" alt="Screen Shot 2022-02-08 at 9 03 20 AM" src="https://user-images.githubusercontent.com/5077880/153005309-e2a50215-e347-4dfb-96e7-ed2960a1b306.png">

**Comment by bigint** [comment]
@mikeghen i'll take this

**Comment by josealonso** [comment]
@bigint, you might want to finish properly previous tasks before taking nwe ones, I think.

**Comment by bigint** [comment]
@josealonso can you point out uncompleted tasks of mine?

**Comment by josealonso** [comment]
Explanation of the continuous integration tool in *Contribute.md*

**Comment by josealonso** [comment]
> @josealonso can you point out uncompleted tasks of mine?

Explanation of the continuous integration tool in Contribute.md

**Comment by bigint** [comment]
@josealonso that's in progress and it is very minor one, we need to create another PR for that, the existing one was already merged 🙇🏻

**Comment by josealonso** [comment]
> @josealonso that's in progress and it is very minor one, we need to create another PR for that, the existing one was already merged 🙇🏻

The developer that configured the CI tool explained you everything on discord, but you did not add a single line in the document. I honestly do not understand your behavior.
