### ISSUE TITLE
fix mweb design for main page

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#353]
currently, the design in mweb/tablet looks like this, no proper alignment, items are placed unorder, looks very bad.

<img width="390" alt="Screenshot 2022-02-10 at 1 59 11 PM" src="https://user-images.githubusercontent.com/55599878/153371495-b73a0630-dfde-4122-83a5-2be2d0cf5290.png">

proposed fix with proper alignment and design ✨ - 

<img width="390" alt="Screenshot 2022-02-10 at 2 24 38 PM" src="https://user-images.githubusercontent.com/55599878/153371926-3630032b-2311-41c5-ac09-bc0e5f03c5db.png">

**Comment by abhisheknaiidu** [comment]
i've created a PR, let me know what you think 😄

**Comment by josealonso** [comment]
> i've created a PR also, let me know what you think smile

Thanks for joining. I think this is something subjective. Personally, I don't see a major difference. What is your name on discord ?

**Comment by abhisheknaiidu** [comment]
@josealonso my pleasure. yes i've done alignment and ordering changes, which i feels is looking good now compared to previous one. 
btw my discord username is - NADS#6614

**Comment by bigint** [comment]
Looks better than previous one 🚀

**Comment by josealonso** [comment]
@abhisheknaiidu, it's definitely better, sorry I didn't pay attention. You can tell I'm not a UX specialist :(

**Comment by mikeghen** [comment]
Nice work @abhisheknaiidu :clap:
