### ISSUE TITLE
Bug https://staging.ricochet.exchange 

### ISSUE THREAD

**Issue by msoni89** [Ricochet-Exchange/ricochet-frontend#356]
# Bugs -  

1: If the user is not connected with any wallet, TOTAL VALUE STREAMING is not showing any numbers.
2: For the fresh user, if the user connects wallet. User cant edit/update/withdraw streams and balances, all buttons are disabled. 
3: For the fresh user, if the user tries open stream  -  TOTAL VALUE STREAMING is also showing "Loading..."
4: For the fresh user, even I connected with the wallet it show a "You have to connect wallet...." message.
![issue_3](https://user-images.githubusercontent.com/65469737/153492769-8137ff17-238a-422d-a604-ec22eec18217.png)
![issue_2](https://user-images.githubusercontent.com/65469737/153492774-b24a1297-0550-4c58-b708-966bcc7f2efe.png)
![issue_1](https://user-images.githubusercontent.com/65469737/153492777-9fe9f44c-1a35-48e9-84fd-1ec5b023e9d6.png)

Gnosis safe - Fixed
steps:

delete WEB3_CONNECT_CACHED_PROVIDER from local storage and test it.

**Comment by mikeghen** [comment]
@msoni89 its all you :+1: Thanks for your review

**Comment by msoni89** [comment]
Fixed tutorial icon (mobile)
![image](https://user-images.githubusercontent.com/65469737/153675334-bdee7575-3911-49c7-ac55-25a00f1d8347.png)
Fixed top padding of text (mobile)
![image](https://user-images.githubusercontent.com/65469737/153675356-ede5ec57-0323-4f9e-bd69-da176c456bc7.png)

All above are also fixed. 

Not sure, but refer not visible on a mobile screen, is it intentional?

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/153677452-8415350a-2da2-42be-b303-fb3fa081adbf.png)
