### ISSUE TITLE
deploy staging.ricochet.exchange on IPFS + fleek using CI

### ISSUE THREAD

**Issue by samirsalem** [Ricochet-Exchange/ricochet-frontend#361]
Workflow proposal:
- Create a new QA branch
- Create a pr against QA branch
- Automate some checks on code (audit  security, eslint checks etc)
- Create a preview env using current ci
- Once pr is merged to QA branch
- We trigger deploy to staging env using fleek
- Once staging env is validated the changes can be deployed in production

**Comment by samirsalem** [comment]
i would like to work on this :)

**Comment by geekypandey** [comment]
Hi, what checks are required in audit security? just `npm audit`? 
There are also multiple options available directly on Github like CodeQL Analysis, Codacy Security Scan etc. for static code analysis. Are they required?

**Comment by mikeghen** [comment]
@geekypandey, I will take a look at your PR today or tomorrow, I have to do the fleek setup and might not get to it today, thanks for working on this.
