### ISSUE TITLE
Design polishing

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#365]
1. Bottom left - the little margin between the selection shading and the white section of the app makes the app look a little scroungy
2. The coloring on the app is off. The gradient on the top of the app doesn't fit with our scheme. Could you use the color scheme from slide 14 of our slide template: https://docs.google.com/presentation/d/1li9eKNKijYsuGiSH11YZpIs9mdSADzpVSnqHmI-6gP0/edit#slide=id.g10afdc4ef9e_0_16 and switch to solid colors (no gradient)
3. The overall spacing of the header needs to be widened. It's nice with the current app, but with what's in staging, it's really squeezed

![image](https://user-images.githubusercontent.com/62968241/153653122-76440005-c75e-4f6c-9065-5b4450b743d1.png)

4. The white section has these nice rounded edges (screenshotted) in the current dApp. I would really like to see this maintained in the new dApp. 

![image](https://user-images.githubusercontent.com/62968241/153653173-6d979e11-dfac-4edc-adf0-1f58ac11c1cc.png)

**Comment by adarshzpatel** [comment]
Hello is this issue still open to take or resolved ?

**Comment by josealonso** [comment]
I just put my avatar instead of @Seroxdesign. He's doing it, not me.

**Comment by josealonso** [comment]
@Seroxdesign, I think this issue can be closed. Please let me know to make sure.

**Comment by Seroxdesign** [comment]
@josealonso Yes this has been resolved and merged
