### ISSUE TITLE
different alignment for tutorial item on both desktop and mweb compared to other items in the list

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#376]
ideally, the icon should come first and then text same as other items. for desktop, the current alignment makes sense tho as it is an external link, but for mweb we can change, looks weird now.

<img width="128" alt="Screenshot 2022-02-12 at 11 21 33 AM" src="https://user-images.githubusercontent.com/55599878/153698945-538f5731-5a5c-4efa-9909-d9cee74911f8.png">

<img width="400" alt="Screenshot 2022-02-12 at 11 20 10 AM" src="https://user-images.githubusercontent.com/55599878/153698897-0e122e09-2744-4957-a451-12181c4ccb0f.png">

**Comment by abhisheknaiidu** [comment]
@mikeghen I'd like to work on this issue 😄

**Comment by mikeghen** [comment]
I think its fine the way it is, I see what you're saying but I think its fine as it is, color looks different though so maybe an issue should be made for that
