### ISSUE TITLE
Support for Sending Streams

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#389]
Implement a send feature on the wallet page similar to how Superfluid implements this in app.superfluid.finance:

![unknown (1)](https://user-images.githubusercontent.com/5077880/153898923-297969fc-2ac1-4a9d-8429-cce6f1b9f8fb.png)

**Comment by Seroxdesign** [comment]
I would like to work on this!

**Comment by Seroxdesign** [comment]
Updating. 

I'm reading through the superfluid sdk documentations. 

I'll begin building and testing the feature throughout this weekend and.

Will have results on the 02/23

**Comment by Seroxdesign** [comment]
Updates:

I am still working witht the superfluid Core SDK, an issue that's arised is the lack of clear documentation related to making this work with all networks. 
There is a hands on tutorial the shows how to use this feature with ethers, as well as a youtube video that goes over the tutorial.
I am still trying to find the feature in use on a live website but no luck yet.

Tomorrow I will be designing the frontend for the feature and doing some more expirementation with the feature.

**Comment by Seroxdesign** [comment]
Today I designed the pop up in figma then developed the frontend for desktop:

![fhdohgldi](https://user-images.githubusercontent.com/69639595/155907641-83e97a65-f632-4bc4-b8bf-cf8fa8ac4479.jpg)

Tomorrow I will be changing the colors to match our styles, designing and building the receive pop up.
Should have it done by the end of this week

**Comment by Seroxdesign** [comment]
Still working on this, have been pretty busy with all the bugs but should still have everything before beginning of next week

**Comment by 0xSero** [comment]
Got this working, now I need to make it pass tests/look good + clean up

**Comment by 0xSero** [comment]
I'd like 3 more days with this if no one else needs it.

**Comment by 0xSero** [comment]
Committed a working version! Need to make it look better and add the other options
