### ISSUE TITLE
Distributions Page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#391]
Create a page that shows IDA subscriptions with all the same information that's available in app.superfluid.finance's dashboard (shown below)

<img width="1447" alt="Screen Shot 2022-02-14 at 8 27 20 AM" src="https://user-images.githubusercontent.com/5077880/153899083-61028bff-207a-4650-b917-b8286c67553b.png">

**Comment by Seroxdesign** [comment]
I would like to work on this!

**Comment by josealonso** [comment]
The code of the new Superfluid console is here: https://github.com/superfluid-finance/superfluid-console

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/155418327-c4ee7753-6a60-4173-97dc-1b17086c68c5.png)
![image](https://user-images.githubusercontent.com/65469737/155418383-cb35ca8f-afaf-4149-be09-aa3c5a2156a9.png)
Responsive 
I will finish it tomorrow

**Comment by Seroxdesign** [comment]
Good working, love this thank you

**Comment by mindsgn** [comment]
hey @msoni89 whats the status of this?.

**Comment by mikeghen** [comment]
All set @mindsgn
