### ISSUE TITLE
Supertoken Portfolio Balance

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#392]
Show Supertoken portfolio balance at the top of the wallet page. Sum up the supertokens in the users wallet and display the balance in aggregate at the top of the wallet page

<img width="354" alt="Screen Shot 2022-02-14 at 8 28 10 AM" src="https://user-images.githubusercontent.com/5077880/153899321-75db0a21-bf21-4c4c-a64c-b4b34c34cf33.png">

**Comment by sakshiverma25** [comment]
@mikeghen I wish to take this

**Comment by josealonso** [comment]
@sakshiverma25, what is your discord name ? You can stop by Ricochet discord. We have many technical discussions there.

**Comment by josealonso** [comment]
The code of the new Superfluid console is here: https://github.com/superfluid-finance/superfluid-console

**Comment by bigint** [comment]
![Screenshot 2022-02-19 at 4 55 40 PM](https://user-images.githubusercontent.com/69431456/154798860-063a2ae3-5287-4711-b047-4b83d6399273.png)

@mikeghen I added the total balance here
