### ISSUE TITLE
Recent Stream Activity

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#393]
Show recent CFA and IDA events in a "Recent Activity" page/section in the app. Probably this can be put below the tokens table on the Wallet page

<img width="634" alt="Screen Shot 2022-02-14 at 8 28 29 AM" src="https://user-images.githubusercontent.com/5077880/153899611-cbb2a589-b364-4d43-82e6-deb613d3ba3c.png">

**Comment by zhyd1997** [comment]
If this issue is opened to anyone, I am glad to work on it 😀

**Comment by josealonso** [comment]
The code of the new Superfluid console is here: https://github.com/superfluid-finance/superfluid-console

**Comment by zhyd1997** [comment]
@josealonso seems that it's different than what we want.

**Comment by zhyd1997** [comment]
Submitted a pull request!
