### ISSUE TITLE
Show "Streamed so Far" metric to "Streams" page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#394]
On the streams page in the app, add a metric to each stream to show how much has been streamed so far into the app
<img width="1816" alt="Screen Shot 2022-02-14 at 11 01 55 AM" src="https://user-images.githubusercontent.com/5077880/153900159-8e2ccc90-af03-4792-b403-f5367d905214.png">

IDK where the best place is but I highlighted two places here:
<img width="1403" alt="Screen Shot 2022-02-14 at 11 03 05 AM" src="https://user-images.githubusercontent.com/5077880/153900193-f94dd5e3-3b33-4136-b419-2630672bd9e2.png">

**Comment by bigint** [comment]
@mikeghen I'll take this 🚀

**Comment by bigint** [comment]
@mikeghen that's in progress, makes sense i'll delete the comment so other devs can pick, if no one picks it I'll do 🤗

**Comment by sakshiverma25** [comment]
@mikeghen I wish to take this

**Comment by mikeghen** [comment]
Please, someone do this

**Comment by joshuasamaniego** [comment]
I can take a stab at this one!

**Comment by mikeghen** [comment]
Good luck

**Comment by mikeghen** [comment]
@joshuasamaniego, still interested in taking a look at this?

**Comment by mikeghen** [comment]
#545 has some code that might be relevant for this

**Comment by joshuasamaniego** [comment]
Yes, still interested, just busy with Tellor work. Okay great, what should I be looking at with #545?

**Comment by msoni89** [comment]
[Done] https://github.com/Ricochet-Exchange/ricochet-frontend/pull/569

@mikeghen Please review and merge

**Comment by mikeghen** [comment]
Nice work @msoni89
