### ISSUE TITLE
different color navbar on both desktop and mobile

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#396]
in mobile -

<img width="400" alt="Screenshot 2022-02-12 at 11 12 26 AM" src="https://user-images.githubusercontent.com/55599878/153918147-ba914812-d0d6-42e7-bc81-ef88869abc10.png">

in web -

<img width="128" alt="Screenshot 2022-02-12 at 11 21 33 AM" src="https://user-images.githubusercontent.com/55599878/153918156-f18983e1-0dee-410d-9ca2-b4ff6b43975b.png">

**Comment by abhisheknaiidu** [comment]
@bigint i would like to fix it 🙏🏽

**Comment by bigint** [comment]
@abhisheknaiidu is the is happening in https://staging.ricochet.exchange/ ?

**Comment by abhisheknaiidu** [comment]
@bigint yess, it's happening 😶

**Comment by josealonso** [comment]
Well done, @bigint !!
