### ISSUE TITLE
Support for Coinbase Wallet link and WalletConnect?

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#40]
With Coinbase soon supporting Polygon withdrawals, might be good time to look into adding these as an alternative to Metamask. Might also be able to render the app showing some basic info without having to login at all, allowing easier use on mobile.

**Comment by FullNodeMeditator** [comment]
I suggest a web3 modal such as this: [https://github.com/ChangoMan/web3modal-example]

The WalletConnect and the Coinbase wallet integration are crucial for fiat to Polygon ramps as both provide near-term solutions for US citizens (and others) to bring liquidity efficiently to Ricochet.

**Comment by cryptoguru0125** [comment]
Hi, I can help you

**Comment by FullNodeMeditator** [comment]
Excellent.   Welcome aboard. Can I ask how you found out about this bounty?  Here are the details for working on bounties [https://docs.ricochet.exchange/business/bounty-hunters](https://docs.ricochet.exchange/business/bounty-hunters)

A good next step might be to connect with us in Discord as well:
https://discord.gg/vFFyxpKT    

Shepardblue is our led dev and might be able to answer any questions.

**Comment by mikeghen** [comment]
@cryptoguru0125, thanks for volunteering, let me know if you have any questions

**Comment by mindsgn** [comment]
hey @cryptoguru0125 any progress with this bounty?.

**Comment by harshitsinghai77** [comment]
Hey, if you want maybe I can help with this stuff.

**Comment by FullNodeMeditator** [comment]
@

> Hey, if you want maybe I can look into this and help with this stuff.

Yes, please.  We still need support with this bounty.  Hop into the discord server and discuss if you have any questions.  Otherwise, go right ahead and start coding.

**Comment by 0xMihir** [comment]
Currently working on this + improving UX 
![image](https://user-images.githubusercontent.com/93171064/147038383-ad6c2f64-df01-446c-bce7-bc9ed7b6d911.png)

**Comment by mikeghen** [comment]
Because of the complexity of the issue, @abstractpoint and I would like to raise the bounty

**Comment by sunnyjaycer** [comment]
Hey @0xMihir, what's the status of this?
