### ISSUE TITLE
no spacing b/w contract and create vault element

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#401]
<img width="398" alt="Screenshot 2022-02-15 at 8 44 54 AM" src="https://user-images.githubusercontent.com/55599878/153985995-1bf8899b-7604-4ad2-86ec-da1289aba302.png">

**Comment by abhisheknaiidu** [comment]
@mikeghen  @bigint i would like to fix it 🙏🏽

**Comment by zhyd1997** [comment]
Hi @abhisheknaiidu
The contract copying will be removed here https://github.com/Ricochet-Exchange/ricochet-frontend/pull/400

**Comment by abhisheknaiidu** [comment]
@zhyd1997 cool, closing this issue then 😄
