### ISSUE TITLE
too much info on a small section is leading to a bad UI and UX

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#411]
![Screenshot 2022-02-16 at 10 43 39 PM](https://user-images.githubusercontent.com/55599878/154319369-b736ff7f-02d2-4e88-a0f0-e7c0f5703fd4.png)

**Comment by abhisheknaiidu** [comment]
@mikeghen @bigint I'm thinking to show in 3 rows with 2 items each, it will look much better wdyt??

**Comment by bigint** [comment]
We are working on bank page redesign so we will handle those there 🙇‍♂️
