### ISSUE TITLE
redesign header, navbar and hamburger menu across all pages 🚀 

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#413]
currently the UI for header and navbar looks like this - 

![Screenshot 2022-02-16 at 11 01 21 PM](https://user-images.githubusercontent.com/55599878/154322434-35321e42-6bd1-497d-8f6f-1d8ad6831dbb.png)

![Screenshot 2022-02-16 at 11 01 27 PM](https://user-images.githubusercontent.com/55599878/154322443-490d0e15-1483-4623-bf2d-60d12826e708.png)

**proposed redesign/mockup with cool transition and animation** ✨  -

https://user-images.githubusercontent.com/55599878/154322626-1b180b5e-c7f8-497b-b676-7591c3c981cc.mov

**Comment by abhisheknaiidu** [comment]
@mikeghen @bigint what do you guys think of this??? 😄

**Comment by mikeghen** [comment]
@Seroxdesign, what do you think? I like it

**Comment by Seroxdesign** [comment]
Yes! That looks so much better.  

Thank you @abhisheknaiidu

**Comment by abhisheknaiidu** [comment]
@mikeghen @Seroxdesign thanks, if it looks good then i would like to work on this.
