### ISSUE TITLE
Make the app ready for internationalization  

### ISSUE THREAD

**Issue by josealonso** [Ricochet-Exchange/ricochet-frontend#425]

**Comment by josealonso** [comment]
This is not a new feature since there is a *i18n* directory since many months ago. But for some component the developers forgot to use it.
Therefore, this task consists of modifying the components that are not prepared for internationalization. 
Thanks to @Seroxdesign for notifying this.

**Comment by ramprakashram** [comment]
@josealonso Can I Take up this task ??

**Comment by josealonso** [comment]
> @josealonso Can I Take up this task ??

I just assigned it to you, thanks for joining :) You might want to stop by our discord server.

**Comment by ramprakashram** [comment]
Thanks @josealonso , I just joined there.

**Comment by ramprakashram** [comment]
Hi @josealonso , I have raised a PR for this, please check it.

**Comment by josealonso** [comment]
> Hi @josealonso , I have raised a PR for this, please check it.

Thanks for telling me !! I left my comments in the linked PR.
