### ISSUE TITLE
Round Flow Rates

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#429]
Flow rates in the app need to be truncated for division to work correctly in the smart contract.

The rule is that the amount must be divisible by the `shareScaler` * 1e3

For example, if shareScaler = 1e9, then the amount must be rounder to 1e12. The flow rate:
```
222222222222222
```
Must be rounded to:
```
222000000000000
```
The `shareScaler` can be retrieved from `getOutputPool`.

More examples of the rounding, assume 1e9 shareScaler:
<img width="579" alt="Screen Shot 2022-02-17 at 2 57 42 PM" src="https://user-images.githubusercontent.com/5077880/154577892-0ce21e19-dc2e-468a-ac1c-cbe303ec1cb5.png">

⚠️ The user if entering 100 should get a little message that says, the rate is rounded to 98 so it can be evenly divided or something

This is a result of the bug fix for how shares are calculated in the smart contracts: 
https://github.com/Ricochet-Exchange/ricochet-protocol/pull/74

**Comment by elvijsTDL** [comment]
I will try to do this one during the weekend

**Comment by mikeghen** [comment]
@elvijsTDL, let me know if I can help you

**Comment by elvijsTDL** [comment]
Seems like I have messed up somewhere as my rounding seems off , but hoping to finish it up tomorrow

**Comment by josealonso** [comment]
@mikeghen, can I merged the PR linked to this issue ?
