### ISSUE TITLE
Total streams metric

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#43]
This issue involves porting the "Total streams" metric to the new UI

<img width="363" alt="Screen Shot 2021-10-26 at 10 00 20 AM" src="https://user-images.githubusercontent.com/5077880/138894696-5b419bda-dae2-41c7-b6f1-e5dfc53a0861.png">

**Comment by mikeghen** [comment]
The code for this can be found in the earlier versions of Ricochet Exchange

**Comment by jo-chemla** [comment]
Screenshot of PR: 
![image](https://user-images.githubusercontent.com/16822841/140313642-814c580c-560e-4dd1-96aa-9266eee3f0f5.png)
