### ISSUE TITLE
Add torus wallet support

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#438]
https://toruswallet.io/

**Comment by d3centra** [comment]
Is Torus Wallet integrated with any major dApp?

**Comment by josealonso** [comment]
@bigint , please justify your decisions. There are many on-line wallets. Why did you choose this one ?

**Comment by bigint** [comment]
@josealonso we will add standard ones one by one

I've seen Portris and Torus is the best non-custodial wallet provider out there

Those two are widely used in dApps out there like ENS, Superfluid etc

![image](https://user-images.githubusercontent.com/69431456/154799037-a59c04a6-cbf4-41cc-bbaf-a7e5c1c13a64.png)
![Screenshot 2022-02-19 at 5 02 07 PM](https://user-images.githubusercontent.com/69431456/154799045-f8da7763-ac86-41c0-860f-d2d53973576c.png)

> There are many online wallets.

Can you list some standard ones? we can consider it after doing a security audits 🤗

**Comment by josealonso** [comment]
> @josealonso we will add standard ones one by one
> 
> I've seen Portris and Torus is the best non-custodial wallet provider out there
> 
> Those two are widely used in dApps out there like ENS, Superfluid etc
> 
> ![image](https://user-images.githubusercontent.com/69431456/154799037-a59c04a6-cbf4-41cc-bbaf-a7e5c1c13a64.png) ![Screenshot 2022-02-19 at 5 02 07 PM](https://user-images.githubusercontent.com/69431456/154799045-f8da7763-ac86-41c0-860f-d2d53973576c.png)
> 
> > There are many online wallets.
> 
> Can you list some standard ones? we can consider it after doing a security audits hugs

Thanks for making the effort to explain it, @bigint. Wanting to support the same wallets as Superfluid does is a valid reason.

**Comment by josealonso** [comment]
Thanks for making the effort to explain it, @bigint. Wanting to support the same wallets as Superfluid does is a valid reason. Just try to do it every time you open an issue. @mikeghen's items are good examples of that.

**Comment by bigint** [comment]
Thanks will do it next time @josealonso 🚀
