### ISSUE TITLE
Lock `node` version

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#445]
We should lock `node` version in `package.json` and `.nvmrc` for better compatible and development experience.

**Comment by bigint** [comment]
cc @samirsalem

**Comment by josealonso** [comment]
@bigint, I have the impression that @zhyd1997  wanted to solve this issue because he opened it. Please try to be more considerate with your team colleagues. Just put yourself in his shoes and imagine what you would be thinking now.

**Comment by bigint** [comment]
@josealonso did they claimed anywhere in discord or GitHub?

https://docs.ricochet.exchange/business/bounty-hunters

**Comment by zhyd1997** [comment]
@bigint did you claimed anywhere?
