### ISSUE TITLE
Total flow rate shown twice on mobile

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#446]
<img width="304" alt="Screen Shot 2022-02-19 at 7 37 00 AM" src="https://user-images.githubusercontent.com/5077880/154805464-1455f7e7-2972-49a7-90f2-6604f3c6a0c5.png">

**Comment by mikeghen** [comment]
Remove the first time it appears

**Comment by bigint** [comment]
will fix it @mikeghen

**Comment by bigint** [comment]
love the new font 🚀
