### ISSUE TITLE
i18next::translator: missingKey en

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#456]
<img width="1265" alt="i18" src="https://user-images.githubusercontent.com/31362988/154913592-fe7d7700-5faf-4edc-80ee-063bbc3615ee.png">

**Comment by zhyd1997** [comment]
@josealonso Please assign to me, thank you!

**Comment by zhyd1997** [comment]
No bounty needs!

**Comment by josealonso** [comment]
> No bounty needs!

Sorry, I didn't understand you.

**Comment by zhyd1997** [comment]
@josealonso just adding 2 lines can fix this issue!

**Comment by josealonso** [comment]
> @josealonso just adding 2 lines can fix this issue!

I see, I understand now. All the texts and labels should have an entry in the *i18n* file. Good finding !!

**Comment by josealonso** [comment]
@zhyd1997, I noticed the github link points to the discord page. It's not your fault, but can you please fix that ? Also, when you click on "Docs", could the doc be opened in a new tab, instead of downloading it ? I put a small bounty.

**Comment by zhyd1997** [comment]
No problem @josealonso

**Comment by zhyd1997** [comment]
@josealonso 
1. github link has been fixed
2. `Docs` link will be opened in a new tab, no need to fix.
3. seems that our whitepaper file is broken.

**Comment by josealonso** [comment]
> @josealonso
> 
>     1. github link has been fixed
> 
>     2. `Docs` link will be opened in a new tab, no need to fix.
> 
>     3. seems that our whitepaper file is broken.

It's not broken. It is downloaded, instead of being opened in a new tab. I confused `Docs` with `Whitepaper`, sorry.

**Comment by zhyd1997** [comment]
@josealonso could you open the `Whitepaper`?

I can't open it both on my local machine and online website.

But it was opened in a new tab correctly in my dev environment.

**Comment by josealonso** [comment]
> @josealonso could you open the `Whitepaper`?
> 
> I can't open it both on my local machine and online website.
> 
> But it was opened in a new tab correctly in my dev environment.

You're right, the pdf document is damaged.
