### ISSUE TITLE
Bring users active stream markets to the top

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#46]
If a user is streaming to a market, then that market should show up at the top of the list. This issue involves sorting the markets for each user based on how much they're streaming to it. Even better might be to put markets with active streams at the top in a special box to call them out separately

**Comment by jo-chemla** [comment]
PR Screenshot: 
![image](https://user-images.githubusercontent.com/16822841/140324602-088bb73e-39de-4735-a6d3-8f13373e72fb.png)

**Comment by mikeghen** [comment]
looking good on app.ricochet, nice work @jo-chemla :+1:
