### ISSUE TITLE
Refactor: reduce redundant code

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#466]
There are many repeat source code snippets in every pages, like so:

<img width="1189" alt="refactor" src="https://user-images.githubusercontent.com/31362988/155122776-5f0fb251-0e42-4034-ac2b-a061a15c76a3.png">

It would be better if moving them into the `MainLayout` container.

**Comment by josealonso** [comment]
I just a bounty value, after going through many issues. What do you think, @Seroxdesign and @samirsalem ? I don't know the frontend code, but this refactoring tasks are really helpful for us programmers.

**Comment by Seroxdesign** [comment]
All for refactoring
