### ISSUE TITLE
Align token icons

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#47]
This issue involves aligning all the token logos in Ricochet, see the image below. They're all out of alignment:
<img width="323" alt="Screen Shot 2021-10-26 at 4 43 32 PM" src="https://user-images.githubusercontent.com/5077880/138958097-6462a5fc-05b1-4028-8514-679d82d0bde2.png">

**Comment by abstractpoint** [comment]
Fix: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/56

**Comment by mikeghen** [comment]
Much better 
<img width="267" alt="Screen Shot 2021-11-01 at 9 33 23 AM" src="https://user-images.githubusercontent.com/5077880/139679886-d2b5f5b7-2395-4178-869a-ce247f1a6c7b.png">
