### ISSUE TITLE
ui bugs

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#481]
- [x]  fix NAN value in supertoken balance

<img width="180" alt="Screenshot 2022-02-24 at 11 06 23 PM" src="https://user-images.githubusercontent.com/55599878/155578780-47e8de89-8b98-4b30-b610-f95143457b42.png">

- [x]  format number here

<img width="180" alt="Screenshot 2022-02-24 at 11 04 55 PM" src="https://user-images.githubusercontent.com/55599878/155578813-be19201a-7a7e-4863-8db7-2bc6058a010e.png">

- [x] fix dropdown while loading

<img width="421" alt="Screenshot 2022-02-24 at 11 06 58 PM" src="https://user-images.githubusercontent.com/55599878/155578918-da29ac50-7cfd-4350-985e-210c35f40bd6.png">

- [x] fix alignment on mweb for collateral price

<img width="107" alt="Screenshot 2022-02-25 at 9 34 02 AM" src="https://user-images.githubusercontent.com/55599878/155651548-5d4c0285-f717-4de5-ae06-56ab70b5c65f.png">

**Comment by abhisheknaiidu** [comment]
i would like to fix these

**Comment by josealonso** [comment]
@abhisheknaiidu, I may be wrong, but I think the third issue you describe was introduced by you.
