### ISSUE TITLE
Last Distributed at not working

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#494]
This was working before ETH Denver, now its not

<img width="190" alt="Screen Shot 2022-02-25 at 5 16 41 PM" src="https://user-images.githubusercontent.com/5077880/155810573-7247ae03-5b07-47e1-ac04-904dfc0fcf69.png">

**Comment by elvijsTDL** [comment]
#528 Fixed this

**Comment by mikeghen** [comment]
Thanks @elvijsTDL
