### ISSUE TITLE
Realign Token symbols

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#509]
I feel like we keep having to do this over and over 😪 

<img width="353" alt="Screen Shot 2022-02-26 at 11 02 58 AM" src="https://user-images.githubusercontent.com/5077880/155850110-2195db58-11ba-4dc5-9337-c1e92641aafe.png">

**Comment by abhisheknaiidu** [comment]
@mikeghen i would like to fix this
