### ISSUE TITLE
Re - Visiting Invest/Launchpad Pages Freezes the app

### ISSUE THREAD

**Issue by Seroxdesign** [Ricochet-Exchange/ricochet-frontend#515]
**Describe the bug**

Whenever you visit Invest and Launchpad Pages and connect your wallet the app will slow down significantly, then freeze completely and finally the browser crashes.

**To Reproduce**

1. Go to 'https://staging.ricochet.exchange/invest/rex-market'
2. Navigate to a different page
3. Return to invest page 
4. Open your browser console 
5. View errors

**Expected behavior**

Users should be able to navigate to any part of the website and back wihout issue

**Comment by Seroxdesign** [comment]
Update:  This only happens when you leave Invest page and go back to it

**Comment by Seroxdesign** [comment]
The new contracts added in this PR are causing the app to freeze up:

https://github.com/Ricochet-Exchange/ricochet-frontend/pull/513

@mikeghen does this have anything to do with the keys?

**Comment by mikeghen** [comment]
but this isnt actually an issue so no bounty should be paid

**Comment by Seroxdesign** [comment]
No bounty was claimed
