### ISSUE TITLE
Bring back links to contracts in Bank UI

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#519]
These links were lost when the UI was upgraded
<img width="937" alt="Screen Shot 2022-02-28 at 10 19 45 AM" src="https://user-images.githubusercontent.com/5077880/156008805-4855a108-ca2d-4cd8-8c94-f886aeb31761.png">

**Comment by abhisheknaiidu** [comment]
@mikeghen added links in #553
