### ISSUE TITLE
Loading feedback when transactions are pending

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#52]
This issue involves adding loading animations while a transaction is pending, currently the experience is just greyed out buttons.
<img width="1387" alt="Screen Shot 2021-10-29 at 11 27 15 AM" src="https://user-images.githubusercontent.com/5077880/139462017-4a39c556-9532-4511-915e-fec425a910f5.png">

**Comment by mindsgn** [comment]
I will take this on.

**Comment by mindsgn** [comment]
PR: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/122

**Comment by mikeghen** [comment]
Nicely done @mindsgn
