### ISSUE TITLE
Approve Repay for the Bank is Broken

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#520]
Reopening #287, this issues happening in staging.ricochet.exchange

**Comment by mikeghen** [comment]
Bounty for figuring out who broke this

**Comment by mikeghen** [comment]
We really all need to do better and stop breaking things that other people have fixed, I believe this is the 3rd time someone broke this feature

**Comment by spitko** [comment]
Fixed in #557
