### ISSUE TITLE
Upgrade button needs to be disabled if not approved

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#527]
The upgrade button isn't disabled if no approval is done, the result is a reverting transaction opening in metamask if you just click upgrade:
<img width="728" alt="Screen Shot 2022-02-28 at 4 39 59 PM" src="https://user-images.githubusercontent.com/5077880/156063330-00624ebc-16b0-4627-8740-224575323b86.png">

**Comment by mikeghen** [comment]
@spitko, It looks like this issue is back, probably someone else on the team broke your fix, I did test it, it worked. Could you take another look?

**Comment by spitko** [comment]
Sorry, the PR was made to main branch and not v2, created a new PR into v2: #589
