### ISSUE TITLE
Not correctly capturing amount approved for upgrade widget

### ISSUE THREAD

**Issue by sunnyjaycer** [Ricochet-Exchange/ricochet-frontend#54]
On the new UI (on main branch), the upgrade widget is not correctly capturing the amount of token approved by the user to the super token contract. 

Pictured here, the user has not approved enough allowance of MKR to the MKRx contract and yet the UI is showing that the user _has_ approved enough and has enabled upgrade button enabled.

The old UI is able to correctly detect amount approved. Old UI is found at commit 2964803f9e92a02dfc2adeeebf6eb10cfab57804.

INCORRECT - New UI
![image](https://user-images.githubusercontent.com/62968241/139553781-e41aeb20-4bbd-4823-8191-788ecb6cccab.png)

CORRECT - Old UI
![image](https://user-images.githubusercontent.com/62968241/139553726-57c25634-b773-40cb-834e-f7f2d621b28a.png)

**Comment by mikeghen** [comment]
handled in #89
