### ISSUE TITLE
Max Deposit not working at the Bank

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#542]
Two issues:
1. Approval doesn't pop up when the user has no approval
2. The max button fills in the wrong value

<img width="417" alt="Screen Shot 2022-03-02 at 9 27 22 AM" src="https://user-images.githubusercontent.com/5077880/156380794-eff8dcea-7576-46b6-9c9f-aff910d6ebbb.png">

**Comment by Seroxdesign** [comment]
Also working on this

**Comment by 0xSero** [comment]
Fixed:
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/562

**Comment by 0xSero** [comment]
This can be closed @mikeghen
