### ISSUE TITLE
Repay/Withdraw/Borrow/Deposit button opens both form fields on the bank vaults

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#543]
On the vaults page, if you have two vaults for the two banks, clicking repay on the second bank opens up the form for both the vaults

<img width="1585" alt="Screen Shot 2022-03-02 at 9 44 08 AM" src="https://user-images.githubusercontent.com/5077880/156384339-d76f84c6-2085-45c8-a027-655ac79d7e05.png">

**Comment by Seroxdesign** [comment]
All of these are actively being worked on by me. Please assign to me if possible

**Comment by 0xSero** [comment]
Finishing this up rn

**Comment by 0xSero** [comment]
Fixed: 
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/561

**Comment by mikeghen** [comment]
Thanks @Seroxdesign
