### ISSUE TITLE
Incorrect total flow shown on the last market row

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#55]
The total flow currently is 4696.300 
<img width="1071" alt="Screenshot 2021-11-01 at 10 24 15" src="https://user-images.githubusercontent.com/3032975/139657779-ff272802-be8c-4f22-9089-0da1c8e8b312.png">

**Comment by jo-chemla** [comment]
Seems to be correct now on a development build  of main branch. Maybe the exchange is not built from the latest main? 
![image](https://user-images.githubusercontent.com/16822841/140179282-feb48989-3c2b-47cb-95ca-ceac4a4254af.png)

**Comment by abstractpoint** [comment]
Yes its been merged but looks like not deployed
