### ISSUE TITLE
Round Values at the bank

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#550]
Make the numbers look more round, truncate decimals to two decimal places (0.00) and use `K`, `M` for thousands and millions 
<img width="147" alt="Screen Shot 2022-03-03 at 11 49 56 AM" src="https://user-images.githubusercontent.com/5077880/156612413-30938387-8e6f-478b-9057-9812257a7d07.png">
<img width="195" alt="Screen Shot 2022-03-03 at 11 49 52 AM" src="https://user-images.githubusercontent.com/5077880/156612414-1f908da8-860e-4cbd-b791-5fb450c1efa3.png">

**Comment by abhisheknaiidu** [comment]
@mikeghen assign me, will fix this 🙏🏽
