### ISSUE TITLE
Switch to Polygon button not working

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#552]
**Describe the bug**
The "Swith to Polygon" button no longer works

**To Reproduce**

1. Set your wallet to Ethereum or any non-Polygon network
2. Load app.ricochet.exchange
3. Click the "Switch to Polygon" button

**Expected behavior**

This should pop something in metamask to switch the network to polygon

**Comment by msoni89** [comment]
@mikeghen https://github.com/Ricochet-Exchange/ricochet-frontend/pull/554
