### ISSUE TITLE
Disable buttons if user is unable to start a transaction and add tooltips explaining it

### ISSUE THREAD

**Issue by elvijsTDL** [Ricochet-Exchange/ricochet-frontend#571]
A bunch of buttons are enabled when there are negative values set in the fields or they are empty , or the user hasn't got enough balance, which can cause users some confusion and possibly transactions that just get rejected

To prevent such bad UI/UX. unnecessary confusion and messages in discord ,all buttons for upgrading/downgrading/repaying/starting a stream etc. should be disabled if users balance is too low or the field is empty and input fields should not allow user to input "-" sign or invalid characters ( letters , special characters ) into them and should have a tooltip on the buttons indicating why the button is disabled

**Comment by abhisheknaiidu** [comment]
On it.
