### ISSUE TITLE
Distribution page - Distribution so far $ column values wrong for RIC and Matic

### ISSUE THREAD

**Issue by elvijsTDL** [Ricochet-Exchange/ricochet-frontend#574]
@msoni89 a bug missed in #545 -  Distribution page - Distributed so far values for RIC and Matic are not shown in dollars 

![image](https://user-images.githubusercontent.com/77115130/157537547-1d9cdb12-d18d-478d-bfaa-12cc37414ba7.png)
![image](https://user-images.githubusercontent.com/77115130/157537562-be0720be-4eb1-4297-89ca-7e808b7bd05d.png)

**Comment by msoni89** [comment]
@elvijsTDL https://github.com/Ricochet-Exchange/ricochet-frontend/pull/576/files
