### ISSUE TITLE
Sent transactions not shown in the activity page and copy tooltip overlaying itself

### ISSUE THREAD

**Issue by elvijsTDL** [Ricochet-Exchange/ricochet-frontend#579]
**Describe the bug**

Sent transactions are not shown in the activity history: 
![Screenshot 2022-03-09 at 23 45 34](https://user-images.githubusercontent.com/77115130/157541668-02717144-c7a9-41ac-92e0-4bc044838261.png)

**To Reproduce**

Send some super tokens to a different address , for example , repaying some debt to the bank

**Expected behavior**

Sent transactions should be shown in the activity history

Bug number 2:
Copied tooltip not showing up when copying an address and has a black arrow ?

**To Reproduce**
Open activity page and click on any of the addresses

Expected behaviour:
The "Copied" text should show and the "Copy address" tooltip should disappear, also the arrow should probably be the same as the rest of the tooltip

https://user-images.githubusercontent.com/77115130/157542605-8ddd176d-61b8-48d0-a4c2-bfa8ac784b0c.mov

**Comment by elvijsTDL** [comment]
@zhyd1997

**Comment by zhyd1997** [comment]
I will figure out the reason and fix it without bounty, thanks @elvijsTDL

**Comment by zhyd1997** [comment]
@elvijsTDL 
sent transactions work for me.
<img width="602" alt="sent transactions" src="https://user-images.githubusercontent.com/31362988/157577281-c5c1b62e-dde5-4b7a-bf9d-a9c70c5f964b.png">

**Comment by elvijsTDL** [comment]
> @elvijsTDL sent transactions work for me. <img alt="sent transactions" width="602" src="https://user-images.githubusercontent.com/31362988/157577281-c5c1b62e-dde5-4b7a-bf9d-a9c70c5f964b.png">

Will re-check when polygon is back up , maybe my sent transactions were too old and didn't show up in activity history

**Comment by zhyd1997** [comment]
Waiting for your response

**Comment by elvijsTDL** [comment]
@zhyd1997 Looks like my sent transaction was just a little bit too old to get shown in the activity history,sorry for the misleading, reviewed the tooltip changes, definitely better than before 👍

**Comment by zhyd1997** [comment]
@elvijsTDL great thanks ❤️
