### ISSUE TITLE
Make Ricochet icon stick to the top of the page 

### ISSUE THREAD

**Issue by elvijsTDL** [Ricochet-Exchange/ricochet-frontend#580]
**Describe the bug**

Ricochet logo overlays the contents if user is able to scroll the page

**To Reproduce**

Open up app.ricochet.exchange
Scroll down

**Expected behavior**

Logo should stick at the top of the page and not overlay the contents of the page

**Screenshots**

https://user-images.githubusercontent.com/77115130/157551304-4e60a19e-f099-46de-ae32-4a37da7123d6.mov

**Comment by mindsgn** [comment]
fixed: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/592

**Comment by mindsgn** [comment]
@elvijsTDL please review.

**Comment by mindsgn** [comment]
@elvijsTDL I have made the changes you requested.

**Comment by 0xSero** [comment]
I have completed this and it has been merged, issue can be closed
