### ISSUE TITLE
REX Bank Tutorial

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#584]
This task is to create a tutorial for using the REX Bank. There needs to be a video and written tutorial, these will get added to docs.ricochet.exchange, no PR required for this issue just post links to the media here.

**Comment by 0xSero** [comment]
What is the bounty on this task?

https://youtu.be/WXmXw3oqfBI

This is the video guide, I'm setting it here for review. If I explained things right I will move on to writing the content and getting some screenshots to explain how it works.

**Comment by mikeghen** [comment]
@Seroxdesign I labeled it :+1:

**Comment by mikeghen** [comment]
Thanks @Seroxdesign, I added this to the docs too
