### ISSUE TITLE
add stylelint for scss files

### ISSUE THREAD

**Issue by zhyd1997** [Ricochet-Exchange/ricochet-frontend#587]
### Solution:
https://stylelint.io/user-guide/get-started/#linting-everything-else
https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/5#issuecomment-1000025410
<img width="981" alt="solution" src="https://user-images.githubusercontent.com/31362988/157794522-82ff3fac-a8dc-4baf-9f9a-8328d89c78cc.png">

<img width="412" alt="stylelint config" src="https://user-images.githubusercontent.com/31362988/157999108-e7573929-59ab-49f3-9bb4-f57af0a9a27e.png">

### Criteria:
- [ ] 1. Fix all of the issues reported by `stylelint`,
<img width="1034" alt="stylelint check with scss file" src="https://user-images.githubusercontent.com/31362988/157794366-652863ed-198e-48d9-a268-1844a1f4fd23.png">

- [ ] 2. and add a `pre-commit` hook calls `npx stylelint "**/*.scss"`.

**Note**: this blocks the Nextjs migration because of some strange syntax in our `.scss` file.

**Comment by zhyd1997** [comment]
Some strategies to prevent UI break.
1. split the issue into smaller tasks(the same to bounty) and assign them to two or more contributors.
2. assign to one contributor but every commit must be tested by QA.

**Comment by um1ng** [comment]
@mikeghen Hi mike, I have found a lot of stylelint format problems, and I have made a lot of file modifications, such as those shown in the img, but the project cannot run. I think the difficulty of this problem is very high, so I want to ask this question,  how much bounty can i get?
![SCR-20220314-ryh](https://user-images.githubusercontent.com/3151716/158169666-659e86a4-ab83-405e-95f1-6e0a943e967e.jpeg)
![unknown](https://user-images.githubusercontent.com/3151716/158169674-ccd9dc34-8453-4c62-ac50-8e5d80a8d64e.png)

**Comment by elvijsTDL** [comment]
@um1ng Changing stuff to kebab-case and adding spaces doesn't seem like a very hard problem , can't most of these automatically be handled with a simple command?

**Comment by zhyd1997** [comment]
Codemod needs some knowledge of AST, but not everyone knows that, including me.

I think the style lint affects many `.scss` files, we need to confirm that changes do not break the UI.

**Comment by mikeghen** [comment]
I'm all for formatting so let me know when something's ready here

**Comment by um1ng** [comment]
> I'm all for formatting so let me know when something's ready here

Yeah, I am ready do these tasks.

**Comment by zhyd1997** [comment]
@um1ng
I am confirming that if you still working on it, if no, this will be picked by other devs.

If yes, you can submit a PR, and @mikeghen will put a bounty then, like this issue: https://github.com/Ricochet-Exchange/ricochet-frontend/issues/584#issuecomment-1073361626 (Task was finished and Mike put $1000 bounty on it, for example)

**Comment by um1ng** [comment]
> @um1ng I am confirming that if you still working on it, if no, this will be picked by other devs.
> 
> If yes, you can submit a PR, and @mikeghen will put a bounty then, like this issue: [#584 (comment)](https://github.com/Ricochet-Exchange/ricochet-frontend/issues/584#issuecomment-1073361626) (Task was finished and Mike put $1000 bounty on it, for example)

Okay, I'll do it as soon as possible.

**Comment by mikeghen** [comment]
@um1ng @zhyd1997, is this done? I'm adding a $250 bounty to it

**Comment by Himnashu** [comment]
@mikeghen  If no one is doing this, I can pick it up this weekend.

**Comment by mikeghen** [comment]
@Himnashu, go ahead, lmk how it goes

**Comment by 0xSero** [comment]
@Himnashu 

Any progrss on this?

**Comment by mindsgn** [comment]
@Seroxdesign take this on.
