### ISSUE TITLE
The lighthouse CI runs on v2 everytime

### ISSUE THREAD

**Issue by geekypandey** [Ricochet-Exchange/ricochet-frontend#593]
**Describe the bug**
The lighthouse CI runs on the v2 branch everytime. 

**To Reproduce**

1. Create a new pull request
2. Check the logs

**Expected behavior**
Expected behaviour would be to run the CI action on the repository branch from
which the PR is made.

**Screenshots**

![image](https://user-images.githubusercontent.com/24317727/158866330-41d97f4f-1132-49dd-9956-d49429f8799e.png)

**Comment by mikeghen** [comment]
Thank you @geekypandey, I labeled this so you can submit for a bounty payout
