### ISSUE TITLE
Show "amount received so far" below "amount streamed so far"

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#598]
As a customer, I want to see how much I streamed in so far relative to how much I received.

Right now I do this by checking both the streams page and the distributions page. It would help to have these both on the same page.

<img width="256" alt="Screen Shot 2022-03-21 at 10 49 51 AM" src="https://user-images.githubusercontent.com/5077880/159288107-86735eb4-d18a-480a-99bd-496f58f7501a.png">

**Comment by zhyd1997** [comment]
In Progress...
