### ISSUE TITLE
Prevent failing transactions when amount is too low

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#60]
When user enters $2/mo stream amount that results in almost a 0 value per second flow, which gets rejected by contract. We should find a way to warn user and prevent such transaction. Important to fix as new users want to test the app with low amounts, so important to give a good first impression, and not a failed transaction without any explanation.

**Comment by mikeghen** [comment]
The minimum amount that you can use is `1e9` units/second which works can be amortized to a monthly number. Problem with USDC is it only has 6 decimals, so 1e9 is actually a rather significant amount

**Comment by josealonso** [comment]
Can this issue be closed, @mikeghen ?

**Comment by josealonso** [comment]
I put my avatar on behalf of @Seroxdesign

**Comment by elvijsTDL** [comment]
@josealonso #475 #496 These PRs Fix the issue

**Comment by josealonso** [comment]
> @josealonso #496 This PR Fixes the issue

Thanks, Elvis. @Seroxdesign was working on this, not me. Although the main issue with the bank is the bug when trying to repay. That's assigned to him. Closing this one.
