### ISSUE TITLE
Issues in staging on Firefox

### ISSUE THREAD

**Issue by josealonso** [Ricochet-Exchange/ricochet-frontend#601]
**Describe the bug**

On Firefox I can connect my Metamask, but it's not loading the markets. I finally have to quit and close the web browser.

**To Reproduce**

Open a tab on Firefox and go to staging.ricochet.exchange

**Expected behavior**

A list with the existing markets.

**Screenshots**

**Error message**

`Uncaught (on promise) - Error: provider not set or invalid`

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 20.04.2 LTS
- Browser: Firefox
- Version: 98.0.1 (64-bit)

**Additional context**

**Add any other context about the problem here**

The most used web browsers are Chrome and Safari. However, the same staging app is working fine on **https://ricochet-heroku-test.herokuapp.com/**

**Comment by 0xSero** [comment]
This can  be closed

**Comment by josealonso** [comment]
> This can be closed

You're right. I finally tested in Chrome and it's working fine. Few people use Firefox.
