### ISSUE TITLE
Gas estimates not working anymore

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#602]
**Describe the bug**

When transacting on Ricochet, the gas fees are always set too low. It sets gas to 2.5 gwei. This was happening before and it was apparently fixed, for a while it was OK. It could be an issue with where the app is using to estimate gas.

**To Reproduce**

1. Go to the app and start/stop a stream
2. Inspect the gas price and make sure its close to the gas price reported on polygonscan.com at the time.

**Expected behavior**

It should say the txn is going to confirm in 30 or 15 seconds. It should not be red.

**Screenshots**
<img width="305" alt="Screen Shot 2022-03-24 at 3 35 17 PM" src="https://user-images.githubusercontent.com/5077880/159996573-a98b9527-1de0-44f3-b00a-b5dbd03e1de4.png">
<img width="322" alt="Screen Shot 2022-03-24 at 3 35 12 PM" src="https://user-images.githubusercontent.com/5077880/159996574-d5c53a66-fe8d-4881-94ca-458be8fe774f.png">

**Comment by MrSquiggles13** [comment]
Im on it I am familiar with this code

**Comment by mikeghen** [comment]
I think this isn't a problem, might have been an issue with gas estimation endpoint used
