### ISSUE TITLE
Adding Feedback Toasts Across the app

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#614]
We have been getting a lot of requests to add feedback and fix issues that wouldn't exist if we were clearly informing users while they commit actions.

The most prominent places this feature can be added to:

### 4. Referrals: Tooltips and prompt to give users a chance to use a different wallet so their main wallet doesn't get locked

**Comment by 0xSero** [comment]
I'll take care of this if no one else needs it

**Comment by curlypoint** [comment]
@Seroxdesign If you've not started working on it, I'll take it.

**Comment by 0xSero** [comment]
@hkfasdjh Still interested?
