### ISSUE TITLE
Enable sort by balance in wallet view

### ISSUE THREAD

**Issue by yohanesyuen** [Ricochet-Exchange/ricochet-frontend#625]
The wallet view currently displays balance for all supertokens, a user may end up having to scroll quite a bit to see his balance for a particular token when more markets are added.

A solution to allow the user to sort the displayed tokens by balance/any other columns could be useful down the road as more markets/tokens are supported by the platform.

**Comment by hrishibhattu** [comment]
I'm almost done with this.
