### ISSUE TITLE
Make logo scroll with navbar

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#636]
The logo on the top left corner of desktop version does not scroll with Navbar. 

Change it so it scrolls with navbar.

**Comment by curlypoint** [comment]
Hey, I would like to start working on this.

**Comment by curlypoint** [comment]
https://user-images.githubusercontent.com/104732858/166162141-a2e74184-5a83-45c7-8a1a-e9adef2f6981.mov

**Comment by curlypoint** [comment]
Hey, where can I contact you to claim the bounty? @Seroxdesign

**Comment by 0xSero** [comment]
Hey, did you complete this? 
Or are you trying to reserve it?

**Comment by curlypoint** [comment]
I completed this, I think you also merged it, it was PR [637](https://github.com/Ricochet-Exchange/ricochet-frontend/pull/637)
