### ISSUE TITLE
On Mobile Nav/Menu top bar is scrollable | It goes out of view on scroll. 

### ISSUE THREAD

**Issue by Himnashu** [Ricochet-Exchange/ricochet-frontend#639]
**Describe the bug**

**To Reproduce**

1. Go to homepage
2. Click on hamburger icon.
3. Scroll down 
4. Top bar will be removed from view port. 

**Expected behavior**

On menu items should scroll, and the top bar should remain at the top always. 

**Screenshots**

https://user-images.githubusercontent.com/53173981/166325376-7389eda9-493c-4c01-938f-69e6f3e3d017.mov

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hkfasdjh** [comment]
I'll take this bounty

**Comment by Himnashu** [comment]
Fixed, Please review and merge. 
PR :- https://github.com/Ricochet-Exchange/ricochet-frontend/pull/647
