### ISSUE TITLE
Desktop full page is scrollable. Only list and side menu should be scrollable. 

### ISSUE THREAD

**Issue by Himnashu** [Ricochet-Exchange/ricochet-frontend#640]
**Describe the bug**

**To Reproduce**

1. Go to the homepage
2. Scroll down to the bottom
4. See empty space on top of left bar
5. I'm adding both video's for current UX and a better UX. 

**Expected behavior**
we can keep icon and top header fixes and scroll only inner items. 
If we have a large list then the user will not be able to navigate to the top or search bar. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Current UX:-

https://user-images.githubusercontent.com/53173981/166327780-3b24089f-220b-4124-8636-080d48874b14.mov

Expected UX:-

https://user-images.githubusercontent.com/53173981/166327567-2c525b9a-1811-4c8f-8c94-4b2ade86323a.mov

**Comment by Himnashu** [comment]
I can also do many enhancements in the style of this page on mobile and desktop. Please check and approve this first. I'll share a list of improvements in design.

**Comment by Himnashu** [comment]
I can pick this and will try to solve this in 3-4 days max.

**Comment by Himnashu** [comment]
Fixed, Please review and merge. 
PR :- https://github.com/Ricochet-Exchange/ricochet-frontend/pull/647

**Comment by 0xSero** [comment]
Merged this good job
