### ISSUE TITLE
Create Token Swap component

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#648]
![image](https://user-images.githubusercontent.com/69639595/167008329-15b3ece0-49f1-48b2-b1ec-8071f549b540.png)

Create the frontend for this component:

- [ ] Create a container component that contains the swap feature.
- [ ] Pull supertoken data from user wallet to populate component

**Comment by 0xSero** [comment]
@abhisheknaiidu

**Comment by abhisheknaiidu** [comment]
On it @Seroxdesign .
