### ISSUE TITLE
Fix mobile width issue

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#653]
On mobile the wallet page is wider than the screen containing it.

Example:
![image](https://user-images.githubusercontent.com/69639595/167654477-659cd2a7-3b81-4f0d-8158-6d7d691c655a.png)

To fix the bounty we must set a max-width of 100vw

**Comment by curlypoint** [comment]
I'll complete this.
Can you specify the mobile dimensions?

**Comment by shubdixit** [comment]
@Seroxdesign Can you specify on how to reproduce this bug, or dimensions of the mobile view?
