### ISSUE TITLE
Complete Testiny tests.

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#657]
# Context

We have a unit test kit for the frontend
![image](https://user-images.githubusercontent.com/69639595/167982276-4bcdf9b5-804a-4962-87f1-b9ff6e487c8d.png)

I will add you as a tester, each test will be you opening the test and following the steps in the right sidebar no code is necessary just open [the app](https://app.ricochet.exchange) and do whats in this section

- ## Step one

Choose a unit test

![image](https://user-images.githubusercontent.com/69639595/167982521-5827edca-c8c3-4367-8ee5-302adc696cdd.png)

- ## Step two

Open the app, fulfill the conditions and check if expected behaviour matches

![image](https://user-images.githubusercontent.com/69639595/167983013-73a60503-a9cf-47a7-8769-4d9964554042.png)

- ## Step Three

Mark the test as either failed or succeeded depending on the results

![image](https://user-images.githubusercontent.com/69639595/167983201-61e28f03-7e38-41b8-9626-318fb1eed6d2.png)

After you are done list all the tests that failed so we can make a bounty sheet out of them

**Comment by hrishibhattu** [comment]
I'm working on this 🙋‍♂️

**Comment by 0xSero** [comment]
@hrishibhattu Thank you for working on this

I have reviewed and confirmed the work is done.

![image](https://user-images.githubusercontent.com/69639595/168137540-8b33435b-0db7-43ec-9b4a-3a2bde1a0796.png)

**Comment by hrishibhattu** [comment]
Thank you @Seroxdesign 🚀
