### ISSUE TITLE
Improve the P2P streaming feature

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#659]
Currently the p2p feature is a pop up modal

We want to have it in it's own page called "payments":

![image](https://user-images.githubusercontent.com/69639595/168437787-01d5355c-fd84-4f53-af96-564042fd10f3.png)

- [ ]  Remove pop up modal from header
- [ ]  Place the pop up form in a new page called: "payments"
- [ ]  Reorganise the "outgoing streams" table in the "streams" page
- [ ]  Clean up the code

**Comment by abhisheknaiidu** [comment]
@Seroxdesign i'll work on this.

**Comment by 0xSero** [comment]
@abhisheknaiidu You've been assigned to this issue, please update within the next 3 days
