### ISSUE TITLE
Create interaction between Rexswap frontend component and swapABI smart contract.

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#665]
@abhisheknaiidu and I have been working on building this out for the last week.

# We need help with the following

- [ ] Initiating a transaction to the smart contract on address: 0x0983c50085C81A7F41598Eb46a29001989102119
      Take a look at:  https://polygonscan.com/address/0x0983c50085C81A7F41598Eb46a29001989102119#code=

- [ ] Import suprtokens into frontend component /swap:   https://github.com/Seroxdesign/ricochet-frontend/tree/rexswap/src/components/swap the way this would work is the same as:
https://github.com/Seroxdesign/ricochet-frontend/blob/rexswap/src/components/streaming/StreamForm/index.tsx

We check in the wallet to see what supertokens they have then embed those into the form options

to initiate the interaction you must connect to the abi:
https://github.com/Seroxdesign/ricochet-frontend/blob/rexswap/src/components/streaming/StreamForm/index.tsx

-------------------------------------------------------------------------------------------------

You can see other features in the app to get a reference as to how we do that

Finally these discord/github threads will contain everything you need to avoid the mistakes made in the past:

https://discord.com/channels/862796510604296263/939918388824793109

github PR:

https://github.com/Ricochet-Exchange/ricochet-frontend/issues/96#issuecomment-1015733950

https://github.com/Ricochet-Exchange/ricochet-frontend/pull/565

**Comment by hrishibhattu** [comment]
I'm on this

**Comment by mikeghen** [comment]
@hrishibhattu, any update on this?

**Comment by hrishibhattu** [comment]
I'm discussing with @Seroxdesign  and planning to work on it over the weekend.

**Comment by 0xSero** [comment]
I will have something you can test out at the end of tomorrow
