### ISSUE TITLE
Use Superfluid sdk-core for ethereum.ts methods and set gas pricing

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#666]
I think it's best to replace superfluid's js-sdk with its sdk-core to fix the gas price issue depicted below. SDK-core has the gas features we need. Between what's in [src/utils/superlfuidStreams](https://github.com/Ricochet-Exchange/ricochet-frontend/tree/v2/src/utils/superfluidStreams) and [src/api/ethereum.ts](https://github.com/Ricochet-Exchange/ricochet-frontend/blob/v2/src/api/ethereum.ts)

Replace js-sdk with sdk-core in `src/api/ethereum.ts` and use `src/utils/superfluidStreams` for an example how to do it.

Transactions for start/edit/stop flows in the app look like they will fail:
<img width="357" alt="Screen Shot 2022-05-17 at 10 22 37 PM" src="https://user-images.githubusercontent.com/5077880/169305221-ae28e39e-dd62-461d-918c-d85bd1b7137c.png">
<img width="368" alt="Screen Shot 2022-05-17 at 10 22 25 PM" src="https://user-images.githubusercontent.com/5077880/169305223-64dc2c3a-60f5-4b9a-9102-5bde69104b4f.png">

**Comment by mikeghen** [comment]
I think the js-sdk doesn't have support for this until version 0.5.13, when I try to upgrade to the latest js-sdk and run the app I get this error: 
```
Failed to compile.

/Users/mikeghen/Documents/Projects/ricochet-frontend/node_modules/@superfluid-finance/js-sdk/src/InstantDistributionAgreementV1Helper.d.ts
TypeScript error in /Users/mikeghen/Documents/Projects/ricochet-frontend/node_modules/@superfluid-finance/js-sdk/src/InstantDistributionAgreementV1Helper.d.ts(197,19):
',' expected.  TS1005

    195 |         userData,
    196 |         onTransaction,
  > 197 |         gasOptions?: GasOptions,
        |                   ^
    198 |     }: CreateIndexOptions): Promise<Transaction>;
    199 | /**
    200 |  * @dev Distribute tokens to an index
```
So I'm not sure how to resolve this, maybe a typescript issue

**Comment by msoni89** [comment]
@mikeghen 

Raised pull request: https://github.com/superfluid-finance/protocol-monorepo/pull/829 It will fix type error of JS-sdk

**Comment by msoni89** [comment]
@mikeghen please assign it to me.

**Comment by mikeghen** [comment]
Thank you @msoni89 🙏

**Comment by msoni89** [comment]
- src/api/gasEstimator.ts
- src/api/ethereum.ts
- src/utils/fluidSDKinstance.ts
- package.json

Only changes are in the above files, others are formatting.

https://github.com/Ricochet-Exchange/ricochet-frontend/pull/681/files#diff-db040f4db66c373dcde53b0fd9ce405cc487accace0dcc76819cd27af14ff903
