### ISSUE TITLE
Fixing UI issues

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#667]
![image](https://user-images.githubusercontent.com/69639595/169385601-3d94d429-57ca-4019-a35d-94b02c3e4e7a.png)
![image](https://user-images.githubusercontent.com/69639595/169385932-8ae68dbd-48b7-4360-8a12-e705634f980a.png)
![image](https://user-images.githubusercontent.com/69639595/169386093-27aebea4-1898-4d03-b816-a83eb728e5e8.png)

- [ ] Removing the SEND button from top now that we have a new page:

- [ ] Making Navbar on left side scrollable

- [ ] Removing unused component

- [ ] Added extra padding to activity page, to make it look more like everything else

![image](https://user-images.githubusercontent.com/69639595/169386177-59fb8fc2-4c37-4be4-93df-330f5d90f992.png)
![image](https://user-images.githubusercontent.com/69639595/169386297-1ec7df54-89b5-41ca-a525-214491f589fb.png)

- [ ] Making the navbar on mobile better, so users can scroll between different tabs
- [ ] Fixing the colors of the mobile navbar

**Comment by 0xSero** [comment]
On it.

**Comment by mikeghen** [comment]
:+1: thanks @Seroxdesign

**Comment by mikeghen** [comment]
@Seroxdesign is this completed? Im just reviewing things from this week ahead of bounty payouts

**Comment by 0xSero** [comment]
I will send you screenshots of what I've accomplished so far, since this is just UI I'm taking to slow

**Comment by Seroxdesign** [comment]
![image](https://user-images.githubusercontent.com/69639595/170722783-2df11359-626d-4c94-ad54-d253a9d965e7.png)

@mikeghen

**Comment by 0xSero** [comment]
![image](https://user-images.githubusercontent.com/69639595/170722925-83d4b803-f298-4de2-a7b3-cadd549c8961.png)

@mikeghen 


Working on getting this to look like the rest of the app

**Comment by 0xSero** [comment]
Back to working on this now shouldn't be long

**Comment by bertux** [comment]
@mikeghen  do you plan to fix the documentation links at the bottom of the left panel ? If not, I can propose a simple PR to fix them.
