### ISSUE TITLE
Should our wallet screen now support additional incoming tokens from rex?

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#67]
We could add here a way to see your SLPx and REX balances (Maybe not REX as that gets burned)
<img width="515" alt="Screenshot 2021-11-04 at 17 06 59" src="https://user-images.githubusercontent.com/3032975/140386140-874e1735-b2cb-4dfc-99d1-0661cf14e37d.png">

**Comment by mikeghen** [comment]
@abstractpoint, no becauses users will never up/downgrade rexSLP tokens, the upgrade and downgrade is controlled by the stream exchange contracts, rexSLP tokens only exist in your while **while you're streaming**
