### ISSUE TITLE
Show Referral name not ID

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#671]
Instead of showing `10` this should show affiliate ID 10's name, which is `carl`
<img width="625" alt="Screen Shot 2022-05-20 at 3 36 53 PM" src="https://user-images.githubusercontent.com/5077880/169599585-7ab115b6-68ea-49e5-922a-22f40340e059.png">

**Comment by zhyd1997** [comment]
On it
