### ISSUE TITLE
Get Routing working for Fleek/IPFS

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#676]
# Bounty Requirements:

- [ ] Change our current routing package from:  react-router-dom to  https://v5.reactrouter.com/web/api/HashRouter
- [ ] Remove react-router-dom
- [ ] Test changes to see if routing works correctly on Fleek/IPFS + Vercel + current CI pipeline (staging/main)

## Why

We just got IPFS/Fleek Pipeline working, but unfortunately we have an issue, IPFS only understands hash-routing, so we must make the change.

**Comment by zhyd1997** [comment]
On it.

**Comment by mikeghen** [comment]
@Seroxdesign, $1000 is a lot for this bounty which just changed 1 file, @zhyd1997 would you accept $500 instead?

**Comment by mikeghen** [comment]
is bear market seazon

**Comment by zhyd1997** [comment]
> @Seroxdesign, $1000 is a lot for this bounty which just changed 1 file, @zhyd1997 would you accept $500 instead?

Sure 😃

**Comment by 0xSero** [comment]
I assumed it'd be a replacement thanks @zhyd1997

**Comment by mikeghen** [comment]
This was implemented but didn't fix the routing problem on IPFS deploy with fleek as far as I see on https://ricochetxchange.on.fleek.co/invest/rex-market, I'm reopening and renaming to "Get Routing working for Fleek/IPFS"
