### ISSUE TITLE
Add padding to Activity and Distributions to improve overall style

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#689]
Pages we will change:

![image](https://user-images.githubusercontent.com/69639595/170838713-26fbbb00-7e9d-4d2e-9509-0714a63dc089.png)
![image](https://user-images.githubusercontent.com/69639595/170838729-dcb0efcb-2075-4885-bfdb-1ef5f2a03f91.png)

New padding to be the same as:
![image](https://user-images.githubusercontent.com/69639595/170838736-6629b405-50f8-491c-87da-78051ab3f0bd.png)

**Comment by seemwavy** [comment]
Claiming

**Comment by 0xSero** [comment]
> Claiming

You got it.
