### ISSUE TITLE
Complete a testiny run

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#697]
# Bounty Requirements

- [ ] Create a testiny run kit with 95%+ coverage
- [ ] Create a report including all failed/blocked tests

**Comment by mikeghen** [comment]
@Seroxdesign, I think this is done now right?

**Comment by 0xSero** [comment]
It is yes

**Comment by 0xSero** [comment]
![image](https://user-images.githubusercontent.com/69639595/171663106-c315e05e-e316-481a-a5df-5cfccd3d629c.png)
