### ISSUE TITLE
Clickable User Balance for Max up/downgrade

### ISSUE THREAD

**Issue by josefrichter** [Ricochet-Exchange/ricochet-frontend#70]
current behavior: clicking current balance opens coin picker dialog

expected behavior: clicking current balance fills the input field next to it with the value of current balance. this is common behavior on most DEXes, bridges, etc.

**Comment by mikeghen** [comment]
Good issue @josefrichter, this is basically the max button, I would like to **remove the max button** in favor of just click the balance, I think that's most defi users expected way to do a max
<img width="708" alt="Screen Shot 2021-11-05 at 10 32 06 AM" src="https://user-images.githubusercontent.com/5077880/140527302-a291fcf7-cff1-4053-913d-fb8248217f50.png">

**Comment by josefrichter** [comment]
> Good issue @josefrichter, this is basically the max button, I would like to **remove the max button** in favor of just click the balance, I think that's most defi users expected way to do a max 

It's amazing I didn't notice the "max" button at all :-o I guess if there's explicit max button, then it's usually inside the input. Which would be fine solution as well. Maybe even more explicit, and more "correct" from classic UX perspective.

**Comment by mikeghen** [comment]
This issue is actually still open, @qasimmehdi moved the Max button which was a big enhancement, but when you click on the balance, it still pops open the coin list as @josefrichter mentions

**Comment by mikeghen** [comment]
All done
