### ISSUE TITLE
Duplicated Outgoing Streams and Incorrect Stream Rates

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#702]
**Describe the bug**

The outgoing streams section shows streams twice and gives customers the appearence they have multipe streams open. This was already addressed previously so this bug is a regression. Also, the rate in outgoing streams is wrong

**To Reproduce**

Open a stream to any market and then check the streams page. You'll see it looks like there's two outgoing streams.

**Expected behavior**

Should exclude REX Market streams from the Outgoing Streams section. The rates of these streams should be matching, so outgoing streams section is using an incorrect method to convert the stream rate to a $ value.

**Screenshots**
<img width="1356" alt="Screen Shot 2022-06-01 at 1 33 24 PM" src="https://user-images.githubusercontent.com/5077880/171467919-c5476a8e-b3ac-471c-a072-72c820f6600b.png">

**Comment by 0xSero** [comment]
Solved with 
  
  https://github.com/Ricochet-Exchange/ricochet-frontend/pull/710
