### ISSUE TITLE
Market Streams not opening due to APPROVAL issue

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#703]
The second time you start a stream, the app checks if you've already approved things, so its somehow not seeing that you already approved the subscription and its trying to batch call the approve txn with the start/edit stream txn

if you look in ethereum.ts youll see batchCall

**Comment by mikeghen** [comment]
I think we need some more information about how to reproduce this issue

**Comment by 0xSero** [comment]
Browser:  Firefox
Wallet: Metamask

Conditions when bug started:

1. Had used streams many times in the past
2. All streams stopped opening and the error message I would get is that cannot modify flow that doesn't exist.

**Comment by mikeghen** [comment]
@Seroxdesign, this was fixed in #717 :+1:
