### ISSUE TITLE
Show referral ID before stream start

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#726]
Right now if you're referred by someone the Refer page will show you as "Organic" even when the referralId cookie is set. This issue is to change this so that if the cookie is set (i.e. referralId=carl) then show who referred you even before opening a stream.

Currently, people who coming in via referral links look at this refer page to see if that referral worked. So even if the referral id cookie is set, it shows organic and they get confused. Once you open a stream via a referral, then this will show that you were referred by someone.
<img width="2156" alt="Screen Shot 2022-06-13 at 10 42 55 AM" src="https://user-images.githubusercontent.com/5077880/173382540-def4495b-bc1b-4958-8676-89eb7653ce63.png">

**Comment by abhisheknaiidu** [comment]
On it @mikeghen .
