### ISSUE TITLE
Transpose Stream Info into a table view

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#731]
I think the streams page should show the info as a table, similar to the wallet view.

Each stream market right now has stats that stack up:
<img width="1440" alt="Screen Shot 2022-06-17 at 2 14 09 PM" src="https://user-images.githubusercontent.com/5077880/174355153-e6e9b8f8-ad4e-4e02-94d3-0f99084da997.png">
This issue involves transposing the values so each stream market info is in a single row like:

| Market              | Inflow Rate           | Streamed        | Received.         | Balance USDC | Balance ETH   |  TVS |  Active Streams |
|----------------|------------------|----------------|---------------|---------------|----------------|-----------------------|----|
| USDC<>WETH | 10K USDC/month | 554.50 USDC   | 0.451000 ETH |  5000 USDC   | 0.025483 ETH | 27,000 USDC/month  | 14 |

You will need to get Received from the Distributions tab, its highlighted here below:
<img width="1430" alt="Screen Shot 2022-06-17 at 2 13 53 PM" src="https://user-images.githubusercontent.com/5077880/174356039-8da94252-2539-4049-b6fa-28a45147542b.png">

For TVS and Active Streams, try to highlight that differently from the rest of the row since that information represents the entire market, not the users stream activity, its secondary information to the current inflow rate, net streamed, and balance.

Make this look like the wallet view in style.
<img width="1440" alt="Screen Shot 2022-06-17 at 2 29 19 PM" src="https://user-images.githubusercontent.com/5077880/174356778-8c72bb90-81da-4b2b-bc2b-fc97897e609d.png">

**Comment by zhyd1997** [comment]
On it!
