### ISSUE TITLE
Set Referral Cookie using Query Params

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#736]
This issue is required to get Ricochet exchange into the ledger live app store.

Currently, the referralId cookie gets set by visiting https://app.ricochet/exchange/#/ref/ledgerlive

Unfortunately, ledger live's dapp browser can't handle that URL and query parameters must be used. The URL ledger will use to load the app is:
```
https://app.ricochet.exchange/?ref=ledgerlive&embed=true 
```
This issue involves parsing the `ref` query parameter to set the `referralId` cookie. Hitting this link should set the cookie the same way it is currently done by hitting `/#/ref/ledgerlive`.  See the code for that route here: https://github.com/Ricochet-Exchange/ricochet-frontend/blob/0a69ea53baa73feea5fac160b52d9cd50de666cc/src/pages/ReferPage/referralValidationRedirectPage.tsx

**Comment by abhisheknaiidu** [comment]
I'm working on it.

**Comment by blaxkspace** [comment]
I've started working on it
