### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#740]
**Describe the bug**

- [x] Remove scrollbar in the left nav bar, looks weird now

<img width="179" alt="Screenshot 2022-06-24 at 12 47 00 AM" src="https://user-images.githubusercontent.com/55599878/175379787-e9263d78-b6eb-4e0f-98a5-45e1a89e486c.png">

- [x] Not aligned correctly -

<img width="333" alt="Screenshot 2022-06-24 at 12 48 20 AM" src="https://user-images.githubusercontent.com/55599878/175380000-b81ceadb-4c9c-4352-9797-9d1472bb7eed.png">

ideally should aligned like this - 

<img width="333" alt="Screenshot 2022-06-24 at 12 49 23 AM" src="https://user-images.githubusercontent.com/55599878/175380165-0638944a-f9da-4f87-bfbb-d800f179c436.png">

- [x] No padding 

<img width="214" alt="Screenshot 2022-06-24 at 12 51 47 AM" src="https://user-images.githubusercontent.com/55599878/175380536-0e25fb3d-f165-4009-9470-128ea496b61c.png">

ideally should look like this -

<img width="214" alt="Screenshot 2022-06-24 at 12 52 37 AM" src="https://user-images.githubusercontent.com/55599878/175380651-c9f51d38-4be8-4a5d-8d8c-a146fb2881bd.png">

- [x] Tooltip background color is different at the tip, it should be same

<img width="127" alt="Screenshot 2022-06-24 at 12 53 09 AM" src="https://user-images.githubusercontent.com/55599878/175380731-34a10d50-c18a-461b-93b6-7c9a5772eab2.png">

- [x] Not aligned properly

<img width="279" alt="Screenshot 2022-06-24 at 12 56 59 AM" src="https://user-images.githubusercontent.com/55599878/175381329-3a97ec01-6063-4b30-8254-d9f7769c48c8.png">

- [x] No padding at top in refer page in mweb

<img width="387" alt="Screenshot 2022-06-24 at 12 59 42 AM" src="https://user-images.githubusercontent.com/55599878/175381830-e76e5a2f-7766-41dd-afe3-08edaf6947e1.png">

- [x] No padding at top in payments page in mweb

<img width="387" alt="Screenshot 2022-06-24 at 1 00 22 AM" src="https://user-images.githubusercontent.com/55599878/175381988-0b2ea47e-3204-4c1b-9405-c821c25d0a3f.png">

**Comment by mikeghen** [comment]
Thanks for putting this list together

**Comment by 0xSero** [comment]
@abhisheknaiidu @mikeghen Scrollbar is necessary until we change the way the nav works, don't change it.
you can style it so it looks better if you want. But leave the functionality.

**Comment by abhisheknaiidu** [comment]
yes @Seroxdesign scroll will be there, i'll just hide that bar. looks weird now.
