### ISSUE TITLE
Bring back fire icons showing RIC rewards distributions

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#748]
Bring back the RIC rewards flame icon with rewards information:
![ric-flame](https://user-images.githubusercontent.com/5077880/175968799-d94cc963-5624-441a-9afe-2ab9b4a6cb96.png)

**Comment by abhisheknaiidu** [comment]
@mikeghen on it.

**Comment by blaxkspace** [comment]
I can fix this if no one else is on it already

**Comment by mikeghen** [comment]
@blaxkspace, give it a try! Markets are not getting subsidies
