### ISSUE TITLE
Trades page breaks for multiple trades on the same asset

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#754]
I streamed USDC>>WBTC and USDC>>ETH and then stopped the streams, the trades page displayed the correct values. 

Once I started a new stream USDC>>ETH and USDC>>WBTC, the trades Pnl was incorrect, it didn't detect that I had done two trades on both WBTC and ETH. Its confusing the first trade with the second trade. 

<img width="1526" alt="Screen Shot 2022-07-01 at 11 42 12 AM" src="https://user-images.githubusercontent.com/5077880/176927024-756d9bff-96ec-41fb-b5bd-0c4e1e929445.png">

**Comment by zhyd1997** [comment]
https://console.superfluid.finance/matic/accounts/

### clearing the logic: 

the trades page should display `input` data as Fig.1 and display `output` data using Fig.2 data (sum a period of distributions): 

<img width="1200" alt="Screen Shot 2022-07-03 at 19 49 02 Fig.1" src="https://user-images.githubusercontent.com/31362988/177038280-9f8c61b4-52c2-470a-89a5-fdae484ed9c1.png">
<img width="1200" alt="Screen Shot 2022-07-03 at 19 50 14 Fig.2" src="https://user-images.githubusercontent.com/31362988/177038288-5bebdab5-1c91-46b5-ae42-023791c15cd2.png">
