### ISSUE TITLE
UI Issues 

### ISSUE THREAD

**Issue by abhisheknaiidu** [Ricochet-Exchange/ricochet-frontend#771]
- [x] fix nav bar in mweb

<img width="411" alt="Screenshot 2022-07-30 at 7 09 16 PM" src="https://user-images.githubusercontent.com/55599878/181917000-13bf053f-99e9-4e6a-b3b6-932c46af6f48.png">

- [x] Sentences are breaking in mweb

<img width="197" alt="Screenshot 2022-07-30 at 6 22 56 PM" src="https://user-images.githubusercontent.com/55599878/181915497-487bd3cd-8518-4e09-8713-3cd700891d5a.png">

- [x] gaps are present in b/w the tables in mweb

<img width="264" alt="Screenshot 2022-07-30 at 6 37 13 PM" src="https://user-images.githubusercontent.com/55599878/181915712-6058b19a-210e-426b-93a9-22ba44608d75.png">

- [x] Ideally it needs to be look like this - 

<img width="392" alt="Screenshot 2022-07-30 at 6 08 16 PM" src="https://user-images.githubusercontent.com/55599878/181915734-5fbda1a7-3a8d-4ff6-a12f-cf899af83b07.png">

- [x] still blue background is there in mweb and some other places

<img width="412" alt="Screenshot 2022-07-30 at 6 24 31 PM" src="https://user-images.githubusercontent.com/55599878/181915750-ce73c3f2-f984-4f13-b3af-61126d9b21b2.png">

- [x] No spacing b/w tabs and `You have no trades.`

<img width="411" alt="Screenshot 2022-07-30 at 6 54 06 PM" src="https://user-images.githubusercontent.com/55599878/181916369-33825e44-7abb-494b-80e8-fb1e085d0063.png">

- [x] blue color bg still present in the bottom of referral page

- [x] No spacing b/w header n modal

<img width="612" alt="Screenshot 2022-07-30 at 6 30 01 PM" src="https://user-images.githubusercontent.com/55599878/181915488-509ec757-d33a-489f-9456-a9e42837b50e.png">

**Comment by 0xSero** [comment]
## Test 1:

 - Issue:   fix nav bar in mweb
 
 This still doesn't work on Firefox 
![image](https://user-images.githubusercontent.com/69639595/182384779-e7d5d6e3-bd2e-414a-907c-4e0e52b4e010.png)

- Issue:   Sentences are breaking in mweb

This is working well
![image](https://user-images.githubusercontent.com/69639595/182385191-ef3ef3e1-25f8-4f60-86a4-f3654a37cdae.png)

 - Issue:  gaps are present in b/w the tables in mweb

This is working well 
![image](https://user-images.githubusercontent.com/69639595/182386472-d3f0df27-be8f-4c3e-8f86-6c5775b8be6d.png)

 - Isse:  still blue background is there in mweb and some other places
 
 This is working well
 
  - Issue:  No spacing b/w tabs and You have no trades.
  
  This can be done better, the text should be a bit larger and centered:
![image](https://user-images.githubusercontent.com/69639595/182386907-8fd54ff2-304e-4007-8641-d1e9292af711.png)


 - Issue: No spacing b/w header n modal
 
 This has been done well
