### ISSUE TITLE
Animate incoming/outgoing flowrate

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#777]
## Issue: 

Our frontend could use some basic animation to improve UX, by animating the flow from one token into another we can provide users a more visually appealing and less complex application.

### How to solve this:

 - find the per second flowrate for each stream
 - create a function which updates the flowrate on frontend on a second per second basis by incrementing the total streamed so far by the flow rate per second.
  - ensure this function doesn't make additional calls to the backend, all this can be done in the TS
  
### Great example:

You can effectively solve this bounty by backwards engineering the below example and implementing it in Ricochet-frontend:

**Comment by mikeghen** [comment]
Adding screenshots highlighting where to add these animations:

<img width="1615" alt="Screen Shot 2022-09-08 at 6 03 41 PM" src="https://user-images.githubusercontent.com/5077880/189237201-43d062b1-2070-4a94-8bbd-412b5a0bee0c.png">
<img width="1371" alt="Screen Shot 2022-09-08 at 6 02 02 PM" src="https://user-images.githubusercontent.com/5077880/189237203-5391a94a-c8c0-4b38-bc95-fe991be56fc0.png">
<img width="1332" alt="Screen Shot 2022-09-08 at 6 00 16 PM" src="https://user-images.githubusercontent.com/5077880/189237204-18b91c92-22ce-4bd3-b73c-6ad31b450d9b.png">
