### ISSUE TITLE
Fix missing exchange rates

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#786]
Some exchange rates in the app are missing, find a fix this so they show an exchange rate: 
<img width="323" alt="Screen Shot 2022-08-31 at 4 28 01 PM" src="https://user-images.githubusercontent.com/5077880/187775915-086ea631-e2fb-4b04-a37a-905ebecf3a19.png">

**Comment by curlypoint** [comment]
I'm taking up this issue if it's still up.

**Comment by Bhakti087** [comment]
were you able to fix this issue @hkfasdjh ?
