### ISSUE TITLE
Refactor payment page and related components.

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/ricochet-frontend#800]
## Part 1: feature request

 Improve payments page by using MUI form template that's been used in the new swap feature.

### Use the same form layout from the swap container here in the payments page:
![image](https://user-images.githubusercontent.com/69639595/191292907-74f32644-f01e-4abe-b645-119609d474a4.png)

from token, to token and input amount the fields should be:

1. recepient
2. monthly payment amount
3. token to stream.

Below the form there will be open streams, make these in a 1 column table and show the amount, token and recipient, with the close and open buttons.

The code for the new form will be in this PR:
https://github.com/Seroxdesign/ricochet-frontend/blob/swap/src/pages/SwapPage/layout/Checkout/SwapForm.tsx

Just implement it in the StreamForm:
https://github.com/Seroxdesign/ricochet-frontend/tree/swap/src/components/streaming/StreamForm

This will really make a difference in the consistency of the UI.

## 2 -Extra points earned:

If you could refactor the code to be in the same format as the SwapPage that would help a lot.
You can reuse the code from the current Payments page and streaming component but format the folder like this.

https://github.com/Seroxdesign/ricochet-frontend/tree/swap/src/pages/SwapPage

Instead of having the streaming folder and streamContainer put all refactored code in this folder structure:

./src/pages/payments/checkout/form
                                   /index.js

**Comment by PJijin** [comment]
It would be interesting for me to work on this issue if it is still open.  😀

**Comment by hrishibhattu** [comment]
Hey @PJijin, I'm working on this and am nearly done with it 😄
