### ISSUE TITLE
Autoconnect to Gnosis Safe

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#809]
This issue involves making sure that the app automatically connects to Gnosis Safe when loaded up as a browser.

To test this issue, make a Safe on Polygon that you can test with: https://gnosis-safe.io/app

When you load the app into the Gnosis safe apps interface, the safe’s wallet address should automatically connect to the app, without the user having to click “connect” in the top right.

Currently, the experience is you have to click “connect” and wait a while before it connects.

To earn this bounty, the Safe will need to connect within 3 seconds or less, or there will need to be a loading icon indicating the app is waiting to connect to the safe.

**Comment by hrishibhattu** [comment]
Hi @mikeghen , is there a bounty associated with this issue?

**Comment by mikeghen** [comment]
https://app.dework.xyz/ricochet-exchange-da/main-space-32902?taskId=22fdd5e0-9c00-4f07-a640-7e6b18e6a63c

If you want to handle that issue apply in dework, we can have two people work and the bounty will go to the first to deliver.

**Comment by top1st** [comment]
@mikeghen Please check my pull request
#811 
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/811
