### ISSUE TITLE
WIP Add Ramp.network widget to the site

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#83]
Ramp.network allows users to onboard funds directly from their bank account into mainnet or polygon mainnet (Only outside of US currently). They have a JS SDK that can be used to add a button on the site.

For an example behaviour take a look at Zerion dapp.
![Screenshot 2021-11-16 at 21 36 08](https://user-images.githubusercontent.com/3032975/142069649-709b2309-ac0e-4ba8-b7a7-7038054f4a15.png)

**Comment by mikeghen** [comment]
Yes, this deserves a $2500 bounty so I'll make a label for that 💰

**Comment by mikeghen** [comment]
I've already reviewed the docs and this is exactly what we want, it doesn't currently support US-based withdraws to polygon, but I imagine it will soon as will EVERYONE, Ramp has by far the most flexibility and will help us keep the experience within Ricochet, if I understand how this will work correctly.

**Comment by abstractpoint** [comment]
Soon™️
<img width="975" alt="Screenshot 2021-11-17 at 20 59 49" src="https://user-images.githubusercontent.com/3032975/142281709-5a9c550e-def3-44b0-8c82-3f7de7234326.png">

**Comment by mikeghen** [comment]
This is amazing @abstractpoint

**Comment by jo-chemla** [comment]
Any hint about why you are using [Ramp.network](https://docs.ramp.network/sdk-reference/) over [Transak](https://www.notion.so/Integrate-Transak-f43cbb5dc7fa4d068a044ef9589879bf)? Just wondering which one is recommended depending on the project!

**Comment by abstractpoint** [comment]
Still in progress. Facing a strange issue with the SDK at the moment. Asked on Ramp discord, I think might be ok in prod.

**Comment by abstractpoint** [comment]
@jo-chemla They have a simple SDK and are really well known in the space. I was one of their early beta testers/users. We will look into other solutions soon after, depending on how much Ramp would be used I guess.

**Comment by abstractpoint** [comment]
PR here: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/87

Not completely tested all the way through as I was getting a strange error locally with my Bank. I will deploy my own version to prod and test to confirm it works.

**Comment by mikeghen** [comment]
Really well done
