### ISSUE TITLE
Should we add Moon Pay to the site?

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#84]
I have noticed that Zerion app offers both, Ramp network and Moon Pay to onboard funds.

Is Moon Pay available in US and on Polygon? Should we also consider integrating with it?
![Screenshot 2021-11-16 at 21 35 59](https://user-images.githubusercontent.com/3032975/142069690-a8248507-4506-49e9-bc53-a3c6799fc517.png)

**Comment by mikeghen** [comment]
I shared the specifications for v2 and it includes added in embedded cash onramp like Ramp.network, Dharma, etc., so we should certainly add something like Moon Pay

**Comment by mikeghen** [comment]
I think we should just do #83, I'll close this and we'll focus on Ramp.network 🎯
