### ISSUE TITLE
Display RIC distribution rates and end of distribution period

### ISSUE THREAD

**Issue by jo-chemla** [Ricochet-Exchange/ricochet-frontend#91]
Display RIC distribution rates and end of distribution period. 
Probably using a small 🚰 robinet emoji icon, which would display these distribution rates in a popover on hover.

**Comment by mikeghen** [comment]
This can be done with the price, that's the easiest metric to understand, or as price in the input units

**Comment by mikeghen** [comment]
@jo-chemla, I added this to version two and bumped up the bounty a lot

**Comment by sunnyjaycer** [comment]
![image](https://user-images.githubusercontent.com/62968241/143987890-301a9444-1be9-4da4-9142-28a683c45c0a.png)

Just missing that rewards end date

**Comment by mikeghen** [comment]
Nice work @jo-chemla 👏 👏
