### ISSUE TITLE
Clean up market views on mobile

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#93]
These two exchanges are just a little messy looking on mobile, this issue involves laying this information out more cleanly on mobile.
<img width="552" alt="Screen Shot 2021-11-19 at 5 00 13 PM" src="https://user-images.githubusercontent.com/5077880/142697363-fe86ff61-39f4-406a-8bb4-82f1e52fa9d8.png">

**Comment by mindsgn** [comment]
has this been resolved?.

**Comment by mikeghen** [comment]
I think #110  solves this but Im doing QA on it right now

**Comment by mikeghen** [comment]
<img width="400" alt="Screen Shot 2021-11-30 at 9 43 10 AM" src="https://user-images.githubusercontent.com/5077880/144068289-f849d09f-7162-4341-837f-3372226e6d16.png">

**Comment by mikeghen** [comment]
Nice work as usual @mindsgn
