### ISSUE TITLE
Audit and reduce JS bundle size

### ISSUE THREAD

**Issue by abstractpoint** [Ricochet-Exchange/ricochet-frontend#94]
The new UI seems significantly slower than the old one and the current JS bundle has grown to over 2mb in size.

With loads of users from countries with slower internet connection and using mobile discovering Ricochet we need to make sure site is fast and doesn't use so much data transfer.

We should audit bundle using tools like webpack bundle analyzer and try to remove what is not used anymore.
https://blog.saeloun.com/2020/08/04/how-to-investigate-your-build-size-in-webpack.html

**Comment by abstractpoint** [comment]
I have also noticed that on my 5mbit connection atm it takes many seconds to actually download this js chunk. Could be related in some way, or throttling on the hosting plan maybe, not sure 
<img width="710" alt="Screenshot 2021-12-13 at 13 40 32" src="https://user-images.githubusercontent.com/3032975/146593628-f7b4c7c9-4111-4df0-b760-a8485063255d.png">

**Comment by abstractpoint** [comment]
Update. The app now takes 2 minutes to load on Fast 3G connection. I have started looking into trimming the bloat. Looks like bundle now is a whopping 9MB
<img width="1430" alt="Screenshot 2022-01-04 at 14 01 57" src="https://user-images.githubusercontent.com/3032975/148096027-5d80cf5c-b423-4d97-b179-18a01f116986.png">

**Comment by abstractpoint** [comment]
This is somewhat blocked at the moment, due to requirement to migrate to Superfluid SDK-core or SDK-redux instead of JS-SDK which is deprectated.

**Comment by mikeghen** [comment]
Im going to close this and we can revisit it later
