### ISSUE TITLE
REX Launchpad Page 

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#95]
Create a separate page for REX Launchpads that shows the active launchpads. This should be a listing of active launchpads. Separate it out from the main “invest” page.

**Comment by abstractpoint** [comment]
I'm interested to pick this up, since I'm so much into these launchpads.

**Comment by abstractpoint** [comment]
PR here: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/123

**Comment by mikeghen** [comment]
Nice work
<img width="1363" alt="Screen Shot 2021-12-11 at 2 14 13 PM" src="https://user-images.githubusercontent.com/5077880/145688769-2364acfa-74b0-4e7a-9949-385942e56dcf.png">
!
