### ISSUE TITLE
REX Trade Page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#96]
- Create a swap tool that lets users swap super tokens for other super tokens
- This should present as a uniswap style swap page in the app

The REXSuperSwap contract to use for this is deployed here: 0x0983c50085C81A7F41598Eb46a29001989102119

**Comment by mindsgn** [comment]
I am keen on trying this.

**Comment by mikeghen** [comment]
@mindsgn, still interested in this?

**Comment by mindsgn** [comment]
yes I am, currently busy with it.

**Comment by shreyaspapi** [comment]
Regarding https://github.com/Ricochet-Exchange/ricochet-protocol/pull/35, frontend will have to use https://docs.uniswap.org/sdk/guides/auto-router for getting the optimal params including `path`, `poolFees` and `amountOutMin`.

**Comment by MrSquiggles13** [comment]
@mindsgn are you still doing this one? I need a progress update

**Comment by mindsgn** [comment]
@MrSquiggles13  yes, I am looking to get things completed end of this week.

**Comment by josealonso** [comment]
@mindsgn, can I assign to you ? This task is quite big, do you need some help ?

**Comment by mindsgn** [comment]
@josealonso yes please assign it to me.

**Comment by blaxkspace** [comment]
Working on it, pl. confirm bounty

**Comment by 0xSero** [comment]
This will be delivered by September 30th at the latest. If I can't deliver I will pass it on to someone who can
