### ISSUE TITLE
Interactive Stream Manager

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#97]
- Show users a visualization of their streams and allow them to create, edit, delete flows from the visualization
- The idea is to have inputs and outputs, the lines connecting them are the flow rates and they can be edited 
![2527f45c-758f-4f8b-9cc6-d56ba4d7fe1a](https://user-images.githubusercontent.com/5077880/143113629-66297691-0afd-42c6-a055-c7ff3da20630.png)

**Comment by jasonngov** [comment]
@mikeghen I'd be interested in picking this up.

**Comment by jasonngov** [comment]
Is this being worked on? Looking to pick it back up

**Comment by sunnyjaycer** [comment]
Here's the original figma of the concept: https://www.figma.com/file/Wbr92wkrSLLVY3u5EHwft4/Ricochet?node-id=111%3A902

**Comment by josealonso** [comment]
@jasonngov, who is working on this ?

**Comment by jasonngov** [comment]
I believe someone else is working on this.

**Comment by josealonso** [comment]
My avatar is used on behalf of @0xMihir. He's the one doing it, not me.

**Comment by 0xMihir** [comment]
Can I be assigned this?

**Comment by sunnyjaycer** [comment]
> Can I be assigned this?
> 
> 

Done

**Comment by 0xSero** [comment]
I'll take this on if I can get 25% in advance. 

It'll be a long bounty so an advance would help me focus.

**Comment by rakhi2104** [comment]
Hey @mikeghen 
I'm interested in working on this feature. 
I have previously worked on a drag and drop feature for Mattermost [here](https://github.com/mattermost/mattermost-webapp/pull/4042).
