### ISSUE TITLE
Improved Wallet Page

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#98]
- Make the Ricochet DApp Wallet page look more like Superfluid’s wallet page
- Using the +/- buttons for up/downgrade
- monthly netflow is the sum of inbound and outbound streams in the "Incoming/Outgoing..." column
- Have a table of assets in the wallet
- Yes, we want to show inbound streams to the user, not just their outbound streams to Ricochet because that's useful info to the user so they know how much they can budget into our products if they have an income stream.
- Notes:
    - You want to retrieve flow rates from Superfluid subgraph: https://docs.superfluid.finance/superfluid/docs/subgraph
         - Here's an example currently in use with the front end repo: https://github.com/Ricochet-Exchange/ricochet-frontend/blob/8dedb1f6275208190188bdb0175ad17379001ae3/src/utils/getQueryGrath.ts#L1
         - Here's an example from an analytics script Sunny made: https://github.com/sunnyjaycer/ricochet-analytics/blob/main/stream-rates.js
<img width="1414" alt="Screen Shot 2021-11-10 at 6 05 24 PM" src="https://user-images.githubusercontent.com/5077880/143114824-c5435c38-aab2-46cd-931c-8ef62e4893c5.png">

It's highly recommended that you start some streams and experiment with the Superfluid dashboard currency tab screenshotted here to get a feel for what we're looking for here.

**Comment by vaibhavgeek** [comment]
Hi @mikeghen , 
I would love to pick this up, is there a way I can reach out to you so that I can start working on this?

**Comment by jo-chemla** [comment]
Sure, please reach out on the ricochet [discord](https://discord.gg/VaANYUJN)!

**Comment by mikeghen** [comment]
nice work again @vaibhavgeek 👏
